### ISSUE TITLE
Compatibility with plugins that use cookies

### ISSUE THREAD

**Issue by Screenfeed** [wp-media/imagify-plugin#161]
Since version 1.6.6, `imagify_do_async_job()` keeps only WP cookies.
It can cause issues with plugins using cookies, like Duo Two-Factor Authentication.
We have 2 solutions: keep all cookies, bring compatibility for this plugin.

[Duo Two-Factor Authentication](https://wordpress.org/plugins/duo-wordpress/) plugin.
[Fix](https://www.dropbox.com/s/x96k2iksxktlqvy/imagify-duo-2fa.php?dl=0)
[Source](https://secure.helpscout.net/conversation/454213614/51378?folderId=676702).

**Comment by mariusz-ah** [comment]
What about switching to transients in that case? That would be more reliable and perform no conflict with plugins utilize WP cookies.

**Comment by Screenfeed** [comment]
For several reasons:
- It worked perfectly until I had the (bad) idea to restrict to only WP cookies.
- Imagify can already be heavy on the database, let's not try to make it worse (we have several users with huge libraries, we must be centered on performance).
- I'm not sure about being more reliable but it will certainly be hell:
    - Background process means multi-thread,
    - which means problems with transients being cached (and not having the right value, since it is updated in another thread, and then updated in this thread with a not-up-to-date value),
    - so, that means having several transients with unique names (1 transient by thread) to prevent this problem,
    - and multiple transients with unique names means create a cron process that will delete orphan transients periodically.
