### ISSUE TITLE
Add compatibility with "Improve My City" plugin

### ISSUE THREAD

**Issue by Screenfeed** [wp-media/imagify-plugin#188]
A plugin allowing subscriber to upload images: images are not auto-optimized since the users don't have the "upload_files" capacity.

[Source](https://app.intercom.io/a/apps/cd6nxj3z/respond/inbox/1295841/conversations/13845312302).
[The plugin](https://wordpress.org/plugins/improve-my-city/).

**Comment by GeekPress** [comment]
Closing the issue as « Improve My City » plugin has just 90+ active installations after 4 years.
