### ISSUE TITLE
Integrate WP Time Capsule Backup recommandation

### ISSUE THREAD

**Issue by GeekPress** [wp-media/imagify-plugin#269]
Alexis concluded a new partnership with WP Time Capsule. It's a service to backup your website.

We are going to use their affiliate system and implement it into Imagify.

It will add a "Backup & update" link when a new Imagify's version will be available.

The results should be:
- In the plugins list:
![plugins-list](https://user-images.githubusercontent.com/1878479/42044523-8bbb1eb4-7af9-11e8-8b1a-31b993758df9.png)

- In the plugin modal:
![plugin-modal](https://user-images.githubusercontent.com/1878479/42044539-90a39bb8-7af9-11e8-82ca-5b129d3e2fac.png)

- In the WP updates page:
![wordpress-updates](https://user-images.githubusercontent.com/1878479/42044548-956c0f54-7af9-11e8-85fb-d9b7ed41d7be.png)

Here the code:
https://github.com/Revmakx/wptc-partner-snippet/blob/master/plugin/wptc-update-recommendation.js

Feel free to adapt / improve it.

Alexis is going to create our affiliate account. I will provide a DM our affiliate ID.

[Plugin](https://wordpress.org/plugins/wp-time-capsule/).

**Comment by emlebrun** [comment]
➤ Grégory Viguier commented:

Development is done, just waiting for the partner ID.

**Comment by Screenfeed** [comment]
Sorry, bad issue number.
