### ISSUE TITLE
Fix API key setting from environment variable

### ISSUE THREAD

**Issue by timiwahalahti** [wp-media/imagify-plugin#285]
The codebase gives a hint that environment variable `IMAGIFY_API_KEY` could be used for setting API key from a .env file rather than the database. I tried it and it didn't work as expected, Imagify still showed the welcome notification and asked to enter API key from the dashboard.

https://github.com/wp-media/imagify-plugin/blob/master/inc/classes/class-imagify-options.php#L82-L84

**Comment by jbma** [comment]
@timiwahalahti It's not an environment variable, it's a constant.
It should be use like that into your wp-config.php : 

define ('IMAGIFY_API_KEY', 'your_api_key);
