### ISSUE TITLE
Manage user expectations for plan suggestion tool

### ISSUE THREAD

**Issue by glueckpress** [wp-media/imagify-plugin#288]
Today I had a support conversation where a customer seemed quite irritated with Imagify’s plan suggestion.

The tool had suggested one-time plan {whatever} to them, and they had understood that plan would be sufficient to get their entire media library bulk-optimised. But when they had bought it and bulk optimisation had finished, their quota had covered only about 70% of their media library. It wasn’t clear to them that the suggestion was based on an estimation; they had taken it for granted and now felt disappointed about the plugin not having delivered on its promise.

## Current plan suggestion UI

<img width="1334" alt="screen shot 2018-08-30 at 16 51 47" src="https://user-images.githubusercontent.com/308422/44860294-30399a80-ac76-11e8-9ea5-c1cf173a3d9c.png">

Ideally, the plan suggestion tool would be 100% accurate, but that’s not a realistic goal for various reasons; first and foremost, for sake of performance, we can’t just go ahead an scan the _entire_ media library.

So I wondered if the tool’s UI should somehow communicate that the suggestion is based on an estimation? 

## Proposed plan suggestion UI (rough sketch)

<img width="1334" alt="screen shot 2018-08-30 at 16 55 00" src="https://user-images.githubusercontent.com/308422/44860519-a807c500-ac76-11e8-8d77-244cb8ff0aeb.png">

There certainly are ways to word that disclaimer more eloquently, I just meant to illustrate the idea of a sub-heading containing a brief disclaimer. (And we could enhance the wording of the heading itself in one go.)

**Comment by jroddington** [comment]
The heading can change to "Our recommendation for you" as suggested.  For the line under it, that can read as "Based on your recent upload usage."
