### ISSUE TITLE
Increase CSS selector specificity for settings page

### ISSUE THREAD

**Issue by glueckpress** [wp-media/imagify-plugin#294]
It’s a widely shared misconception that nothing else will happen on a plugin’s settings page but the plugin’s settings page itself.

In Imagify’s case, due to lack of selector specificity some of our settings styles get applied to admin notices. This gets a humorous note when we actually cannibalise the notice styles of our own (other) product:

<img width="1443" alt="Imagify button styles applied on WP Rocket admin notice" src="https://user-images.githubusercontent.com/308422/45214126-dfd7c380-b299-11e8-8f5f-00f8f5034b04.png">

As a rule, any plugin-specific admin styles should use deep selector specificity. Other than in general CSS best practices, in the very specific environment of WP Admin more is more. 

For the Imagify settings page, for anything coming below `.imagify-title` an overall selector prefix of `#imagify-settings .whatever` seems in order to avoid the problems illustrated above.

**Comment by Screenfeed** [comment]
> some of our settings styles get applied to admin notices
The only styles applied are the ones for the buttons. Do you think it's better to mix button styles on this page?

**Comment by glueckpress** [comment]
@Screenfeed Yes, clearly. Those admin notices are not from our plugin. They could be styled differently/individually. They are not part of our settings UI, so our CSS should not touch them.

**Comment by Shakup** [comment]
_The BEM naming convention should be used in our development to avoid this problem. Moreover, if we use SASS it facilitates the development._

**Comment by Screenfeed** [comment]
It will require a lot of work, so let's say that the status of this issue is for-the-day-i-really-get-bored-to-death-and-there-is-no-booze-left-or-we-find-someone-that-loves-to-suffer.

**Comment by glueckpress** [comment]
@Screenfeed I am delighted to notice you never got really bored to death, or there was always booze left, and we never found someone who loved to suffer. 🙂  

As this issue has not seen any traction for over two years, I’ll take liberty to close it off. And as unusual as it may appear to exchange pleasantries through a GitHub issue, may I say in these times of uncertainty that I hope you both (meaning @Shakup too) are well and healthy. Take good care, my friends! We shall meet again. 🙏🏼
