### ISSUE TITLE
Use get_option( 'date_format' ) instead of hardcoded date format?

### ISSUE THREAD

**Issue by Tabrisrp** [wp-media/imagify-plugin#34]
https://github.com/wp-media/imagify-plugin/blob/master/inc/functions/i18n.php#L101

**Comment by Screenfeed** [comment]
I don't think we should. This option is used to display the dates **on the blog**. In the administration area, WordPress doesn't use this option, it uses hardcoded formats like the one we use. IMHO, this option value is not meant to display dates within the administration area, we should keep `__( 'F j, Y' )`.

**Comment by Screenfeed** [comment]
So, let's say we close this one Thursday if no more to say?
