### ISSUE TITLE
Add compatibility with WP Rocket CDN

### ISSUE THREAD

**Issue by Screenfeed** [wp-media/imagify-plugin#368]
Since WP Rocket adds the CDN URLs before we parse the page, we don't see them as "local", resulting in images not being replaced by their webp versions.

The filter `imagify_webp_picture_process_image` can be used for this.
At the same time we could use a constant to get URL + path matching, to use in `\Imagify\Webp\Picture\Display->url_to_path()`, it would be a quick way to bring compatibility for our users using other CDNs doing the same thing.

**Comment by jbma** [comment]
We've also this issue with any other CDN service, especially when they are generated by the hosting like WP Engine, or Kinsta

**Comment by Screenfeed** [comment]
Then we must add compatibility for each of them.

**Comment by brianleejackson** [comment]
Any updates on this? We are going to be announcing WebP support soon at Kinsta and would love to include Imagify (as ShortPixel works great), but we might have to move forward without it.

Thanks guys!

**Comment by Screenfeed** [comment]
Hi,
We're currently working on it, it will be included in the next release.
