### ISSUE TITLE
Timeout of 10 sec on /api/version/

### ISSUE THREAD

**Issue by jbma** [wp-media/imagify-plugin#37]
I've a customer with a very slow server, so the api/version/ is doing a timeout in the 5sec => https://github.com/wp-media/imagify-plugin/blob/master/inc/api/imagify.php#L233

So for the plugin our servers are not available, and we display the message "servers are not available" and not possible to optimize.

**Comment by jbma** [comment]
For fast servers, in case our API is really down it could be an issue to put 10 seconds, because they will have to wait 10 seconds.

Maybe a filter here could be the solution.

**Comment by Screenfeed** [comment]
Today it's 5 seconds for this endpoint, but I'll add a generic filter for the timeout value (only).
