### ISSUE TITLE
WP Rocket Hearbeat option and GoDaddy breaks bulk

### ISSUE THREAD

**Issue by jbma** [wp-media/imagify-plugin#370]
On a customer website with GoDaddy, when hearbeat is enabled the bulk optimization isn't working anymore : https://app.intercom.io/a/apps/cd6nxj3z/inbox/inbox/38607/conversations/21971761797

**Comment by jbma** [comment]
Got another one with another customer : https://secure.helpscout.net/conversation/847203504/106977/

**Comment by Screenfeed** [comment]
The only solution is to not use Heartbeat at all, and replace it with a custom script that:
- other plugins won't remove,
- other plugins won't slow down,
- won't slow down nor pause when the window loses focus.
