### ISSUE TITLE
Notice : Undefined variable wp_version in inc/functions/attachements.php on line 108

### ISSUE THREAD

**Issue by jbma** [wp-media/imagify-plugin#38]
Il a l'air de manquer la global wp_version en début de fichier.

**Comment by creativejuiz** [comment]
Accidentaly fixed at https://github.com/wp-media/imagify-plugin/commit/e346ea5e522b1576d32cccb071b80e492d592ada

**Comment by Tabrisrp** [comment]
Fixed in 1.6
