### ISSUE TITLE
stripos() non-string needles

### ISSUE THREAD

**Issue by Screenfeed** [wp-media/imagify-plugin#420]
>PHP Deprecated: stripos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in wp-content/plugins/imagify/classes/Webp/Picture/Display.php on line 633

Fix in `\Imagify\Webp\Picture\Display->url_to_path()`:

```php
		if ( $cdn_url && $domain_url && stripos( $url, $cdn_url ) === 0 ) {
			// CDN.
			$url = str_ireplace( $cdn_url, $domain_url, $url );
		}
```
[Source](https://wp-media.slack.com/archives/C5S1X8WBY/p1564748380005200).

**Comment by Roboonl** [comment]
Any updates on this?

**Comment by Screenfeed** [comment]
Hi.
Since I'm working on WP Rocket until the end of the year, I don't expect to be able to push an update anytime soon.
