### ISSUE TITLE
Wrong percentage info about user quota in the App

### ISSUE THREAD

**Issue by markonikolic985** [wp-media/imagify-plugin#424]
One user reported this.

Everything is fine with his quota usage:

- they can optimize images 
- the calculation is good in terms of MB used

The only issue can be in this screenshot.

![user-quota-percentage-issue](https://user-images.githubusercontent.com/1878479/63023550-a1815600-bea5-11e9-8980-6de1a876f9e2.png)

**Comment by Screenfeed** [comment]
I'm closing it since it seems to be related to the app, not the plugin.
