### ISSUE TITLE
W3 validation issues

### ISSUE THREAD

**Issue by markonikolic985** [wp-media/imagify-plugin#428]
Few errors on user's test.

Example:
`The itemtype attribute must not be specified on elements that do not have an itemscope attribute specified.`

https://validator.w3.org/nu/?doc=https%3A%2F%2Fhdgameshop.at%2Fprodukt%2Fresident-evil-project-resistance

**Comment by Screenfeed** [comment]
This is not an Imagify issue: Imagify doesn’t add the `itemtype` attribute from nowhere, it moves it from the `<img>` tag to the `<picture>` tag. That means the `itemscope` attribute was already missing from the `<img>` tag.
