### ISSUE TITLE
Nextgen Images

### ISSUE THREAD

**Issue by dcagamer** [wp-media/imagify-plugin#43]
We added to an site that had Nextgen gallery and all of the wordpress images (1GB) were optimized but the 2gb of nextgen images were not even touched. Is there an setting to include prior uploaded images from nextgen in the bulk optimization, or are existing nextgen images not compatible yet? 

Imagify 1.6.2
Nextgen 2.1.60

**Comment by dcagamer** [comment]
I have fixed part of the issue but now I am getting an issue trying to optimize the 2gb of images.
![blob](https://cloud.githubusercontent.com/assets/24550877/21152836/0b88bd60-c136-11e6-82df-cb29c23da645.png)

**Comment by jbma** [comment]
Hi,
Can you contact us directly using this form : https://imagify.io/contact/
