### ISSUE TITLE
Add compatibility with Dark Mode plugin

### ISSUE THREAD

**Issue by Screenfeed** [wp-media/imagify-plugin#430]
This plugin allows to have a dark mode in the admin area.
Since dark mode is trendy these days, maybe we could add a basic compatibility with the most downloaded plugin if it doesn't take us much time.
[Dark Mode](https://wordpress.org/plugins/dark-mode/).

**Comment by remyperona** [comment]
Closing this as the Dark Mode plugin has been acquired and rebranded to something completely different.
