### ISSUE TITLE
PHP Deprecated:  stripos in (...)/Display.php

### ISSUE THREAD

**Issue by straightvisions-matthias-bathke** [wp-media/imagify-plugin#439]
Our PHP error log is flooded with the following notice:

`PHP Deprecated:  stripos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /wp-content/plugins/imagify/classes/Webp/Picture/Display.php on line 633`

Would be great if this could be fixed :)

Imagify v1.9.7
PHP v7.3.10

If you need further informations to reproduce, just let me know.

Kind regards,

Matthias

**Comment by Screenfeed** [comment]
Duplicates #420.
