### ISSUE TITLE
Responsive-Bug with srcset and webp-Images

### ISSUE THREAD

**Issue by straightvisions-matthias-bathke** [wp-media/imagify-plugin#440]
Dear Support,

after hours of testing, I am quite confident this is a bug:

**Expected Behavior**
srcset should provide browsers a valid list of different image sizes for different screen resolutions

`<source type="image/webp" srcset="700x467.jpg.webp 700w, 375x250.jpg.webp 375w, 750x500.jpg.webp 750w">`

**Actual Behavior**
First item in srcset-list misses screen width info

`<source type="image/webp" srcset="700x467.jpg.webp, 375x250.jpg.webp 375w, 750x500.jpg.webp 750w">`

You will see that img-tag actually is correct, but source-tag, generated by imagify has issue described above.

Imagify v1.9.7

Kind regards,

Matthias

**Comment by Screenfeed** [comment]
Hello.

You’re right, the bug is actually between the chair and the keyboard: I wrongly thought that the descriptor was optional for the first value.

Thanks for reporting this.
