### ISSUE TITLE
WP Offload Media recent update breaks Imagify

### ISSUE THREAD

**Issue by fbessadok** [wp-media/imagify-plugin#456]
**WP Offload Media** removed the function `get_attachment_provider_info` which resulted in a broken Imagify plugin. We can't optimize images anymore...

**Comment by Screenfeed** [comment]
Hi,
Yes we encountered this issue. We will release a quick fix asap but it will remove the compatibility with WP Offload Media 2.3 (it wasn't compatible anyway, only with WP Offload S3).
Related: #409.
