### ISSUE TITLE
Chunky upload is not supported by HTTP 1.0

### ISSUE THREAD

**Issue by markonikolic985** [wp-media/imagify-plugin#465]
Some users get the following error when using Imagify:

`Our server returned an error (0 - Chunky upload is not supported by HTTP 1.0).`

At this moment, we solve this with a helper plugin, however, it looks like we have increased tickets of this kind (I would say at least 2-3 per week).
[source](https://secure.helpscout.net/conversation/1033678461/136876?folderId=1724287).

**Comment by jonathandhn** [comment]
I'm stuck with that, what helper plugin?

**Comment by Screenfeed** [comment]
@jonathandhn You can find it temporarily [here](https://www.dropbox.com/s/57kj0e495svo35t/http11-for-imagify.zip?dl=1). It can be used as a plugin or a MU plugin.
