### ISSUE TITLE
Resize doesn't work properly for Portrait images

### ISSUE THREAD

**Issue by fbessadok** [wp-media/imagify-plugin#478]
Hi,

I set the resizing option to reduce large images to 1024px in width.
It works great for landscape and square images.
But for portrait images it reduces them to 1024px height and not width.
Can you check please ?

Thank you

**Comment by Screenfeed** [comment]
Hi,
This is the intended behavior if you use WordPress 5.3.
WP 5.3 introduced automatic resizing on upload, pretty much like Imagify does. The only difference is that Imagify "looks" only the image width, while WP also "looks" the height. When WP 5.3 introduced this system, we decided to let WP do this task, to not alter this new "normal behavior".
However there is a way to restore the Imagify’s way of doing by installing [this plugin](https://www.dropbox.com/s/gqjflrdoqv3w0ru/disable-wp-auto-resize.zip?dl=1) (temporarily available at this address). It’s a very small plugin of 1 line of code: it disables WP’s auto-resizing, so Imagify is free to do this task.

**Comment by fbessadok** [comment]
Ok Thank you @Screenfeed I will try that plugin.
