### ISSUE TITLE
Add a Link to Re-Optimize to Aggressive Level if The Normal Level Return: WELL DONE...

### ISSUE THREAD

**Issue by jbma** [wp-media/imagify-plugin#5]
Originally reported by: **Jonathan Buttigieg (Bitbucket: [wp-media](https://bitbucket.org/wp-media), GitHub: [wp-media](https://github.com/wp-media))**

---

---
- Bitbucket: https://bitbucket.org/wp-media/imagify/issue/5

**Comment by Screenfeed** [comment]
Already the case.
