### ISSUE TITLE
Support AVIF image format

### ISSUE THREAD

**Issue by adamradocz** [wp-media/imagify-plugin#504]
Avif image format will be officially supported on the next Chrome (v85). It would be awesome if you could support it.
It's okay even if you don't convert images, just use the manually uploaded ones.

**Comment by markonikolic985** [comment]
Thanks for your suggestion, @adamradocz !

We have more people asking for the same thing, so we will talk about it internally and see what can be done.

Closing this one - feel free to reopen it if you have any questions.

Issue with the same topic can be found in #512

**Comment by Stormrunn3r** [comment]
+1 on Avif support. And is there any new news about Imagify supporting Avif?

**Comment by Lucania001** [comment]
+1 for support, any news?

**Comment by GeekPress** [comment]
It's not scheduled yet as some important browser like Firefox and Safari doesn't support AVIF yet. We still recommend using WebP format for now.

**Comment by adamradocz** [comment]
According to [caniuse.com](https://caniuse.com/?search=avif), 67.25% of the internet supports it. That's quite substantial...

**Comment by wppoland** [comment]
@GeekPress Firefox is going to start its support from ver. 93 so I think it's a good time to start the consideration of supporting such a format: https://caniuse.com/avif

**Comment by omnaiduu** [comment]
Any update about avif support. We need it in imagify

**Comment by SyntaxSamurai43** [comment]
+1 for this one, shortpixel already has this feature. https://blog.shortpixel.com/shortpixel-image-optimizer-the-only-wp-plugin-that-creates-avif-images/

**Comment by samuelmente** [comment]
+1 I would also Love to use Avif on all my clients sites. Please add the support!

**Comment by DanielGoransson** [comment]
+1 Would really help to speed up our websites, and not having to download another image plugin.

**Comment by trybguet-dev** [comment]
+1

**Comment by SyntaxSamurai43** [comment]
When can we expect this feature?

**Comment by michaelbourne** [comment]
It's been a year since we were told "the near future" https://imagify.io/blog/convert-images-to-avif-performance/

Support is now at 73% and rising. https://caniuse.com/?search=avif

I think it's time to add this to Imagify.

**Comment by SyntaxSamurai43** [comment]
I 100% agree, it takes too long! Shortpixel is way more innovative.

**Comment by raptor235** [comment]
Looks like I'll be cancelling my subscription...

**Comment by unitednations-git** [comment]
Same here. Would need to see it deployed now 83% of browser support the format. Considering cancelling my subscription as well for another plugin. https://unric.org Thank you for your feedback!

**Comment by Mtarnuhal** [comment]
Another halve a year has gone by and still no AVIF support. 
https://caniuse.com/avif
With 83% of the browsers supporting it, this would be a great addition for the service.

**Comment by Mil1** [comment]
+1

**Comment by raabmar** [comment]
Competition is already on it for a long time .. I hope we'll see it soon, it seems to make such a huge difference

**Comment by markkes** [comment]
Any update on the process getting avif supported? I would love to support avif images on all of my websites with a gracefull degredation towards webp/jpg/png. 

edit; just seen all the tickets in the issue queue. Looks like there is progress, looking forwards too this feature.
