### ISSUE TITLE
AVIF image conversion support

### ISSUE THREAD

**Issue by lukecav** [wp-media/imagify-plugin#512]
Does Imagify plan on including conversion support for the AVIF image format in the future?
https://netflixtechblog.com/avif-for-next-generation-image-coding-b1d75675fe4

**Comment by markonikolic985** [comment]
Hey @lukecav 

We still didn't consider this option. As we have more people asking us the same question, we will definitely take it in consideration for the future.

Issue with the same topic can be found in #504

**Comment by markonikolic985** [comment]
Closing in favor of #504 (same topic, it's only created earlier). We will share updates on that one from now. 

Thanks for your interest on the topic, we will discuss it internally and see what can be done.
