### ISSUE TITLE
readme.md images broken

### ISSUE THREAD

**Issue by patrick-b-at-work** [wp-media/imagify-plugin#519]
https://github.com/wp-media/imagify-plugin

fix:
raw.githubusercontent.com/wp-media/imagify/master/.wordpress-org/screenshot-1.png
->
raw.githubusercontent.com/wp-media/imagify **-plugin** /master/.wordpress-org/screenshot-1.png
same for the other pictures.

**Comment by remyperona** [comment]
Thank you for the report @patrick-b-at-work, It's fixed with PR #560
