### ISSUE TITLE
Filter for disabling picture/webp replacement on specific template part?

### ISSUE THREAD

**Issue by alexbogias** [wp-media/imagify-plugin#552]
I am trying to add an image as html in [Bootstrap's 4 tooltip](https://getbootstrap.com/docs/4.6/components/tooltips/), but it breaks when this image comes in picture tag. I think that there is something about escaping quotes when title content gets injected thought JS in html. 

I tried  imagify_webp_picture_process_image and imagify_webp_picture_images_to_display with no success.

I am using latest imafigy version 

Can you give me a workaround please?

**Comment by markonikolic985** [comment]
Hey @alexbogias 

You can try with [this helper plugin](https://github.com/wp-media/imagify-helpers/tree/master/webp/imagify-skip-picture-tag-replacement), you might need to change it to match the tooltip's class but should do the trick.

**Comment by alexbogias** [comment]
Hello @markonikolic985 I tried your filter in my child theme function and looks like working great. I also tried adding this data attribute in wp_get_attachment_image function and looks good! Thanks
