### ISSUE TITLE
It's not possible to buy the plan from the plugin

### ISSUE THREAD

**Issue by piotrbak** [wp-media/imagify-plugin#553]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When clicking on the `Go To Checkout`, the broken iframe is displayed and this error is present in the JS console:
`Refused to display 'https://app.imagify.io/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

**To Reproduce**
1. Go to the Imagify plugin settings
2. Click on `What Plan Do I Need`
3. Choose a plan and click on the `Go To Checkout`
4. See an error

**Expected behavior**
We should be able to buy a plan from WordPress plugin

**Screenshots**
![image](https://user-images.githubusercontent.com/26767037/112511617-80bff880-8d8a-11eb-9f31-a2aee060f82b.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by pilamb** [comment]
✅ Scope a solution
A solution would be setting decorator `xframe_options_exempt` on the view serving the content of the iframe.
✅ Effort: [XS]

@Tabrisrp cant edit the tags of this issue.

_Aside note:_

Browsers that support X-Frame-Options
    Internet Explorer 8+
    Firefox 3.6.9+
    Opera 10.5+
    Safari 4+
    Chrome 4.1+
So we should take into account that this solution is partially supported.

**Comment by remyperona** [comment]
@pilamb This is a change to be made on the app side right? Should we transfer the issue to the imagify repository?

**Comment by pilamb** [comment]
> @pilamb This is a change to be made on the app side right? Should we transfer the issue to the imagify repository?

Yes, that's a Django solution.

**Comment by remyperona** [comment]
Albert came up with the reason and solution: the `X-Frame-Options` was set on the new server configuration, but probably not a value that was there before.

For now, this header is removed, and we will test later how to configure to unset the header when requesting the URL endpoint for the iframe in the plugin.
