### ISSUE TITLE
The free plan price is crossed out when the promotion is active

### ISSUE THREAD

**Issue by piotrbak** [wp-media/imagify-plugin#556]
**Is your feature request related to a problem? Please describe.**
When the promotion is applied for all plans, `it looks like` it's also applied to the free plan:
![image](https://user-images.githubusercontent.com/26767037/114042232-2a1fe780-987d-11eb-988e-5270c12c9ba2.png)

We should not consider it as a discounted plan.

**Describe the solution you'd like**
It should just stay as 0$ 

**Describe alternatives you've considered**
We could even remove this plan and replace it with a simple button `downgrade to free plan`

**Comment by iCaspar** [comment]
Copying here rrom conversation on Slack (8 July, 2021) and notes on PR #577 :

**Without PR577:**
The plans are crossed out when choosing them, they shouldn't be as the promo is only for Unlimited. [screenshot](https://jmp.sh/JC1DY92)
When the plan is chosen, then the price is crossed out, while it shouldn't be. (note the price there, it's CORRECT, [screenshot](https://jmp.sh/wF40rCe)
It's not possible to change the promo coupon
**With PR577:**
The plans are not crossed out when choosing them [screenshot](https://jmp.sh/X0ZWmDJ)
When the plan is chosen, then the price is crossed out, while it shouldn't be. note the price there, it's WRONG, [screenshot](https://jmp.sh/iJOpoHz)
It's not possible to change the promo coupon

**With 577 merged, we are now dealing with the second scenario.**

There is also discussion about whether the behavior (and possible other unexpected behavior) menifests depending on the site usage/recommended plan selection.

In any case, the code in `pricing-modal.js` is at issue.

**Comment by iCaspar** [comment]
To be solved in same PR with #557
