### ISSUE TITLE
Coupon code is automatically applied to all plans in the UI, even to those that are not discounted

### ISSUE THREAD

**Issue by piotrbak** [wp-media/imagify-plugin#557]
**Is your feature request related to a problem? Please describe.**
When the promo is applied only to the specific plan, the coupon code and the label `20% off with spring2021` is visible all the time:
![image](https://user-images.githubusercontent.com/26767037/114056288-6b1df900-9889-11eb-8202-b68c08588748.png)
Because of that, we're not able to apply another coupon to different, not discounted plans.

**Describe the solution you'd like**
I think that the coupon + label should be added only when the chosen plan is discounted in the promo. We should be also able to edit this field and apply different coupon

**Comment by piotrbak** [comment]
@Tabrisrp The promo is off, but this change is essential for the new promo. It prevents from buying another plan:
![image](https://user-images.githubusercontent.com/26767037/114692825-e3b10980-9d10-11eb-938f-47453a964ddb.png)

It's happening only on the newest branch that we are working on currently. Before the coupon wasn't applied so checkout worked for all plans.

**Comment by iCaspar** [comment]
The pop-over shown there is being generated from inside the app, and is to do with the handling of the coupon mismatch there. If there is a way to resolve that more gracefully there, we should.
However, on the plugin side, we should implement a UI of our own that will redirect customers from applying a coupon on an order where it is not valid **before** allowing them to proceed to the checkout page.
