### ISSUE TITLE
URL for the app API should be defined in one place.

### ISSUE THREAD

**Issue by iCaspar** [wp-media/imagify-plugin#561]
The URL for reaching the API is defined in (at least) 3 different places.

`inc/functions/common.php`
`inc/classes/class-imagify.php`
`assets/js/pricing-modal.js`

This should be defined once and reused.

**Comment by mostafa-hisham** [comment]
### Scope a solution ✅ 
we can define it  in `imagify/imagify.php`
`define( 'IMAGIFY_APP_DOMAIN',''https://app.imagify.io' );`
and then use it instead re defined it in PHP files

for js file, I don't what is the best way to do it I had a talk with @engahmeds3ed and he told me 
that we can pass it when we register (wp_register_script) the js script `pricing-modal`



### Estimate the effort ✅
effort `[S]`
