### ISSUE TITLE
Correct naming of "WebP" format

### ISSUE THREAD

**Issue by pedro-mendonca** [wp-media/imagify-plugin#562]
**Description**
All the **WebP** related strings on the UI are lowercase **webp**, the correct iamge format name is **WebP**.
https://developers.google.com/speed/webp
In your plugin WP Rocket all the mentions are correctly spelled **WebP**, it should here also, for consistency.

**Screenshots**
![imagem](https://user-images.githubusercontent.com/7371591/115954871-321d8f80-a4eb-11eb-87b0-565f7ccca0bf.png)

**Comment by pedro-mendonca** [comment]
@GeekPress would you be interested in a PR for this?

**Comment by GeekPress** [comment]
Hi @pedro-mendonca 🤚

You are more than welcome to make a PR if you want :)

**Comment by pedro-mendonca** [comment]
Thanks for your anwser :)
Would you prefer only translation strings 'webp' entries or also PHP documentation comments?

**Comment by remyperona** [comment]
For consistency, both would be awesome

**Comment by pedro-mendonca** [comment]
Done, before adding to PR, what about constants like these?
`const TAG_NAME = 'Imagify: webp file type';` (from [here](https://github.com/wp-media/imagify-plugin/blob/master/classes/Webp/IIS.php#L21))


Probably better not to touch these right?

**Comment by remyperona** [comment]
Yes indeed, changing them could affect the correct functionality of the plugin.

**Comment by pedro-mendonca** [comment]
Ok than. PR is complete.
Thanks @Tabrisrp  :)

**Comment by pedro-mendonca** [comment]
Closing this as it's fixed and PR merged.
