### ISSUE TITLE
Add a filter on Imagify notices

### ISSUE THREAD

**Issue by GeekPress** [wp-media/imagify-plugin#564]
**Describe the solution you'd like**

We currently have no way to remove notices displayed by Imagify. For an automatic installation with some of our partners, we need to remove the registration banner.

We are managing the display for all notices based on `all_admin_notices ` hook:
https://github.com/wp-media/imagify-plugin/blob/5971929e9842066e1351704ce14f25c5f31a7180/inc/classes/class-imagify-notices.php#L147

**Comment by mostafa-hisham** [comment]
### Scope a solution ✅ 
I think there is already a filter `imagify_notices` to edit the `$notice_ids` array
in line 875
https://github.com/wp-media/imagify-plugin/blob/3ae8d34d03b389d4f682db70dae8f338ff8bd07e/inc/classes/class-imagify-notices.php#L866-L877

we need to just cast it to array to make sure that other functions will work

`return (array) apply_filters( 'imagify_notices', self::$notice_ids );`


### Estimate the effort ✅
effort `[XS]`

**Comment by iCaspar** [comment]
Demontration code for using the filter to remove the banner. @GeekPress Partners can actually already do this now already 😸 
```
<?php

function cg_test_remove_imagify_banner_notice($notices) {
	$notices = array_flip($notices);

	if ( array_key_exists( 'welcome-steps', $notices ) ) {
		unset( $notices['welcome-steps'] );
	}
	$notices = array_flip( $notices );
	array_filter( $notices );
	//var_dump($notices);die();

	return $notices;
}

function cg_test_hook_stuff() {
	add_action( 'imagify_notices', 'cg_test_remove_imagify_banner_notice' );
}

add_action('plugins_loaded', 'cg_test_hook_stuff');
```
