### ISSUE TITLE
PHP Warning:  array_flip(): Can only flip STRING and INTEGER values! in /public_html/wp-content/plugins/imagify/inc/classes/class-imagify-admin-ajax-post.php on line 471

### ISSUE THREAD

**Issue by joejoe04** [wp-media/imagify-plugin#565]
**Describe the bug**
An Imagify user's error log showed the following warning related to the Bulk Optimizer stats:

`PHP Warning:  array_flip(): Can only flip STRING and INTEGER values! in /public_html/wp-content/plugins/imagify/inc/classes/class-imagify-admin-ajax-post.php on line 471`

**To Reproduce**
Not entirely sure, as I'm not sure what is specifically causing this, but for this user, the Warning is logged when the Bulk Optimizer page is viewed.

**Expected behavior**
This warning message should not be caused when viewing the Bulk Optimizer page.

We could use the `double` `array_flip()` trick or `array_unique()` to resolve this as was done in this [WP Rocket Issue.](https://github.com/wp-media/wp-rocket/issues/3238)

**Additional Context**
Related ticket: https://secure.helpscout.net/conversation/1518484990/265351/

**Comment by remyperona** [comment]
For this one, the `types` should always be a string, so on the following line, I think we can change `array_filter( $folder_types )`, to `array_filter( $folder_types, 'is_string' )`
https://github.com/wp-media/imagify-plugin/blob/ff224f99d3e5baf84d5927835f7debcdc87bd78b/inc/classes/class-imagify-admin-ajax-post.php#L457

**Comment by iCaspar** [comment]
Grooming Notes:

Reproduced: ❌ 
Cannot reproduce locally, but filtering for strings per @Tabrisrp comment should insure array_flip will work.

Effort:
[XS]
