### ISSUE TITLE
Issue with the Imagify Settings page on a mobile device

### ISSUE THREAD

**Issue by ionikol** [wp-media/imagify-plugin#566]
The Imagify Settings page on a mobile device does not look good. A user mentioned it [here](https://wordpress.org/support/topic/suggestions-and-some-questions/)
![Imagify settings](https://user-images.githubusercontent.com/59447333/119774246-8ccf5000-beca-11eb-824a-70432f306866.png)

**Comment by mostafa-hisham** [comment]
### Scope for Solution:
css need to be fixed in settings and imagify-bulk-optimization page
I don't know if there are other pages in the plugins

### Estimate Effort
[S]
