### ISSUE TITLE
Serialization of 'CURLFile' is not alllowed

### ISSUE THREAD

**Issue by Eufranio** [wp-media/imagify-plugin#569]
**Describe the bug**
When trying to optimize images from the 'Other media' page, I get the following error on PHP:

```
[02-Jun-2021 22:15:22 UTC] PHP Fatal error:  Uncaught Exception: Serialization of 'CURLFile' is not allowed in /home/site/public_html/wp-content/plugins/imagify-tools/functions/common.php:101
Stack trace:
#0 /home/site/public_html/wp-content/plugins/imagify-tools/functions/common.php(101): serialize(Array)
#1 /home/site/public_html/wp-content/plugins/imagify-tools/classes/class-imgt-logs.php(653): imagify_tools_compress_data(Array)
#2 /home/site/public_html/wp-content/plugins/imagify-tools/classes/class-imgt-logs.php(609): IMGT_Logs::insert_log(Array, Array)
#3 /home/site/public_html/wp-content/plugins/imagify-tools/classes/class-imgt-logs.php(520): IMGT_Logs->save_logs(Array)
#4 /home/site/public_html/wp-includes/class-wp-hook.php(292): IMGT_Logs->save_current_logs('')
#5 /home/site/public_html/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters(NULL, Array)
#6 /home/site/public_html/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#7 /home/site/public_html/wp-includes/load.php(1072): do_action( in /home/site/public_html/wp-content/plugins/imagify-tools/functions/common.php on line 101
```

**To Reproduce**
1. Go to 'Other media'
2. Selected all unoptimized files from the page
3. Clicked in batch actions -> optimize
4. Error pops in the debug log

**Expected behavior**
The images should be optimized.

**Screenshots**
Not applicable.

**Additional context**
Not applicable.

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
Hi @Eufranio,

The error seems to be coming from Imagify tools, which is an helper plugin for support purpose. If you disable the plugin, do you still have the issue?

By the way, we have an open pull request related to this: https://github.com/wp-media/imagify-tools/pull/43

**Comment by Eufranio** [comment]
It indeed fixed the issue by disabling Imagify Tools. Thank you.
