### ISSUE TITLE
Uncaught Error: Cannot unset string offsets from imagify_count_saving_data()

### ISSUE THREAD

**Issue by jbma** [wp-media/imagify-plugin#57]
The data retrieved in imagify_count_saving_data() (in inc/functions/admin-stats.php) is not always unserialized. 
We simply need to add 
`$attachment_data = maybe_unserialize( $attachment_data );`
 just before 
`$stats_data    = $attachment_data['stats'];`

**Comment by Screenfeed** [comment]
@jbme, we already use `maybe_unserialize()` since March 2016 :|
https://github.com/wp-media/imagify-plugin/commit/b48e50bb8a5a5329597cb8c0544693a6c5e5e730#diff-278989b2de897bb556af51e099876858R125

**Comment by Screenfeed** [comment]
@jbma Do you still have this issue?

**Comment by Screenfeed** [comment]
OK I close this one since the bug doesn't seem to happen anymore.
