### ISSUE TITLE
WP Rocket banner is also displayed when WP Rocket is installed but deactivated

### ISSUE THREAD

**Issue by piotrbak** [wp-media/imagify-plugin#586]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When WP Rocket is installed but deactivated, we are displaying banner in the Bulk Optimization section. The banner is giving 20% of discount for WP Rocket purchases, not sure if people who already have WP Rocket need it.

**To Reproduce**
1. Install WP Rocket
2. Go to Media > Bulk Optimization
3. See banner

**Expected behavior**
I think we should display banner only if WP Rocket is not installed

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
@Mai-Saad FYI, this is ready for review.
