### ISSUE TITLE
Display notification when not supported PHP/WP version is used

### ISSUE THREAD

**Issue by piotrbak** [wp-media/imagify-plugin#589]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
In WP Rocket we're displaying the notice and asking to rollback when we detect not supported PHP/WP version. 

**To Reproduce**
1. Use the newest Imagify (WP 5.3 needed and PHP7.0+)
2. Use PHP 5.6 or/and WP 5.2
3. Check the WP dashboard
4. No notice is present

**Expected behavior**
I think we should display notice just like in WP Rocket

**Screenshots**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by remyperona** [comment]
We already have a notice for this, I tested with PHP 5.6 and the notice is displayed with the rollback button

**Comment by GeekPress** [comment]
@Tabrisrp Thanks for the confirmation. I'm closing it so.
