### ISSUE TITLE
PHP 7.1 Compatibility issue

### ISSUE THREAD

**Issue by jbma** [wp-media/imagify-plugin#59]
When we try to close the ad for WP Rocket, we have this error : 

`Fatal error: Uncaught Error: [] operator not supported for strings in /wp-content/plugins/imagify/inc/functions/admin.php:134 Stack trace: #0 /wp-content/plugins/imagify/inc/admin/ajax.php(442): imagify_dismiss_notice('wp-rocket') #1 /wp-includes/class-wp-hook.php(298): _do_admin_post_imagify_dismiss_notice('') #2 /wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array) #3 /wp-includes/plugin.php(453): WP_Hook->do_action(Array) #4 /wp-admin/admin-post.php(69): do_action('admin_post_imag...') #5 {main} thrown in /wp-content/plugins/imagify/inc/functions/admin.php on line 134`

**Comment by Screenfeed** [comment]
This will be fixed in version 1.6.5: https://github.com/wp-media/imagify-plugin/blob/branch-1.6.5/inc/functions/admin.php#L148.
