### ISSUE TITLE
UI problem with progress bar in the Bulk Optimization section

### ISSUE THREAD

**Issue by piotrbak** [wp-media/imagify-plugin#594]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When the progress bar is at the very beginning, the 0% is displayed in the wrong place.

**To Reproduce**
1. Go to Media > Bulk Optimization
2. Launch the optimization
3. See where 0% is displayed

**Expected behavior**
It should be displayed better, under the 

**Screenshots**
1.
![image](https://user-images.githubusercontent.com/26767037/125274325-c4bd1600-e305-11eb-8704-cd48bd6d021b.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by joejoe04** [comment]
I noticed one other slight issue as well when viewed at narrow widths where the percentage overlaps other content:

![bulk-percentage-overlap](https://user-images.githubusercontent.com/45705494/137965033-b030af9a-eefa-4e1f-b01e-12f46f765207.png)
