### ISSUE TITLE
PHP warnings related to EXIF

### ISSUE THREAD

**Issue by piotrbak** [wp-media/imagify-plugin#595]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
I can see the following warning present in the log:
```
[12-Jul-2021 14:30:23 UTC] PHP Warning:  exif_read_data(single-1-—-kopia-3-—-kopia.jpg): Incorrect APP1 Exif Identifier Code in /var/www/rocketlabsqa.ovh/htdocs/wp-admin/includes/image.php on line 801
```

**To Reproduce**
Not sure how to reproduce this, preserving EXIF is disabled.

**Expected behavior**
No warnings

**Additional context**
File mentioned in the issue:
1. From the uploads directory:
![single-1-—-kopia-3](https://user-images.githubusercontent.com/26767037/125308231-a4528300-e328-11eb-8522-d36cba008026.jpg)

2 From the backup directory:
![single-1-—-kopia-3](https://user-images.githubusercontent.com/26767037/125308260-ac122780-e328-11eb-9174-19c55b85be18.jpg)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by alexbogias** [comment]
same here

**Comment by remyperona** [comment]
I got a similar warning while restoring original on some images. To note, it will only show in the logs if `WP_DEBUG` is enabled, else there is error suppression enabled.

Since it's coming from a call of a function in WP core, it's not something we can do anything about, so I suggest we close this.

**Comment by GeekPress** [comment]
Closing the issue per @Tabrisrp recommandation.
