### ISSUE TITLE
Support for ClassicPress

### ISSUE THREAD

**Issue by mattyrob** [wp-media/imagify-plugin#607]
Hi there and thanks for a great plugin, it has worked well on my site optimising small images for a few years.

I've been a user of [ClassicPress](https://www.classicpress.net/) for a couple of years - this is a fork of WordPress from version 4.9 and therefore avoids the Block Editor experience.

I've noted in release 1.10 that has only just come out that WordPress 5.3 is recommended. As a result I've had to downgrade back to a previous version and I'm sure it will continue to work just fine for the foreseeable future.

However, I wonder if you might consider support for ClassicPress in future versions? I actively contribute to ClassicPress, so is there something specific in WordPress 5.3 and above that more recent versions of your plugin require?

**Comment by GeekPress** [comment]
Hi @mattyrob 

Thanks for your suggestion.

Even if we understand why some people want to use ClassicPress instead of WordPress, we won't work on ClassicPress support.

We will maintain Imagify only on official WordPress solutions.
