### ISSUE TITLE
Documentation link in the Imagify WP Dashboard menu dropdown link is incorrect

### ISSUE THREAD

**Issue by joejoe04** [wp-media/imagify-plugin#608]
**Describe the bug**
It is linking to https://app.imagify.io/documentation/

![image](https://user-images.githubusercontent.com/45705494/127362757-88b59357-ccfb-4206-b6ff-add032314ebc.png)

**Expected behavior**
Should link to https://imagify.io/documentation/ instead

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by ionikol** [comment]
The documentation link also is not working on the Imagify Settings and Bulk Optimization page on the section: 
"Need help or have questions? 
Check our documentation."


It is linking to [https://app.imagify.io/documentation/](https://app.imagify.io/documentation/) and should link to [https://imagify.io/documentation/](https://imagify.io/documentation/)

![shot_210825_083301](https://user-images.githubusercontent.com/59447333/130732693-9b6d89b2-63ed-488d-8ebe-89abc77e2f64.png)
![shot_210825_083355](https://user-images.githubusercontent.com/59447333/130732710-260c6b49-ccba-4b10-9a8a-2e591a32f98d.png)

**Comment by joejoe04** [comment]
Closed this issue since it is closely related to [#618](https://github.com/wp-media/imagify-plugin/issues/618)
