### ISSUE TITLE
Add Ability to Optimize WebP Image Uploads

### ISSUE THREAD

**Issue by joejoe04** [wp-media/imagify-plugin#611]
With WP 5.8, WebP images uploads are now supported. Currently, Imagify is not able to check if any optimization is needed:

![image](https://user-images.githubusercontent.com/45705494/127663482-d0c36aaa-560e-4d19-9d9f-381f8978a0ca.png)

Could possibly be beneficial if the ability to optimize WebP images uploaded to the Media Library was added, as well as the ability for WebP images in "Custom Folders" to be optimized.

**Comment by remyperona** [comment]
the API currently doesn't allow to optimize WebP images directly
