### ISSUE TITLE
Contact us button points to 404

### ISSUE THREAD

**Issue by piotrbak** [wp-media/imagify-plugin#613]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When trying to upgrade directly from plugin, we're displaying the Contact Us button in the pop up that's pointing to 404 (https://app.imagify.io/contact/)

**To Reproduce**
1. Go to the Imagify plugin settings page
2. Click on `What Plan do I need?`
3. Click on `Choose another plan`
4. Click on `Contact us`

**Expected behavior**
We should point to the correct page or use a `mailto` link

**Screenshots**
![image](https://user-images.githubusercontent.com/26767037/128914850-1c1f74be-1e0a-4237-b2d0-36ed11dddef4.png)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by joejoe04** [comment]
Closed because closely related to [#618](https://github.com/wp-media/imagify-plugin/issues/618)
