### ISSUE TITLE
Update Imagify page on WordPress repository

### ISSUE THREAD

**Issue by Crlnwood** [wp-media/imagify-plugin#615]
Hello, 

Could we please update the Imagify page on the WordPress repository?
https://wordpress.org/plugins/imagify/

The new content is here: 
https://docs.google.com/document/d/1artdwb12-ZXocSeqFPV6fW6XFzEhXlNQUnkQmokIgGk/edit

Let me know if you have any questions.

Thank you, 
Caroline

**Comment by GeekPress** [comment]
Some concerns about the excerpt: we removed "optimize images".

The excerpt is one of the most important parts to calculate the ranking. Removing « optimize images » must have a bad impact on the ranking.

I would suggest rephrasing the excerpt to have « optimize images » inside.

The title could be also updated from « Imagify – Optimize your Images & Convert WebP » to « Imagify – Optimize Images & Convert WebP ». Basically, we are removing the « your » to have the exact match to « Optimize Images ».

We are currently 3 on « optimize images » request. It should help to rank better by having the exact match for the term « optimize images » in the title.

ping @Agathemed

**Comment by Agathemed** [comment]
We fixed the description per your recommendation, thanks.

**Comment by Crlnwood** [comment]
Hi, 

Here's the adjusted text:
https://docs.google.com/document/d/1rFvXv3eCUNnNdXBq_2hrF2DLl9a1amiFCuOThg69g5Q/edit?usp=sharing

ping @Tabrisrp
