### ISSUE TITLE
The "More Info" link from the “Error” pop up window points to a 404 page

### ISSUE THREAD

**Issue by ionikol** [wp-media/imagify-plugin#618]
The link "More Info" opens on a 404 error page and needs to point to [https://imagify.io/documentation/solve-imagemagick-gd-required/](https://imagify.io/documentation/solve-imagemagick-gd-required/)

![shot_210827_122539](https://user-images.githubusercontent.com/59447333/134175356-4c01b1e3-9b57-4bf5-95d6-37e03ac6f9bb.png)

**Comment by Mai-Saad** [comment]
@ionikol Thank you for reporting the issue.
Can you please provide the needed steps to see the error message?

**Comment by joejoe04** [comment]
@Mai-Saad Both Imagick and GD need to be disabled for this popup to show. I made this helper plugin that should do this for you. After activating it, try running the Bulk Optimizer and you should see the popup:

[imagify-dont-use-imagemagick-or-gd.zip](https://github.com/wp-media/imagify-plugin/files/7419362/imagify-dont-use-imagemagick-or-gd.zip)

**Comment by Mai-Saad** [comment]
@joejoe04 Thank you for the helper plugin, can see the error message now and More Info link is working fine there,
