### ISSUE TITLE
I update the API key but Imagify don't want to compress other files

### ISSUE THREAD

**Issue by madvik** [wp-media/imagify-plugin#620]
**Describe the bug**
A friend create an account and used all his credit. For help, I decide to lend my API key for some photos.

**To Reproduce**
1. I change the API key.
2. I can verify with the counter :
![image](https://user-images.githubusercontent.com/3822529/134932240-01f9d251-2c94-436c-bfaa-07aae0b38d80.png)
3. I go to the media page
4. I search an image with this : 
![image](https://user-images.githubusercontent.com/3822529/134932436-71551e84-9cc2-4d12-8241-93e3fc125b37.png)
5. I retry and...
6. The result : 
![image](https://user-images.githubusercontent.com/3822529/134932537-b3005b77-d0af-4389-9fd2-ef1202d989a2.png)

**Expected behavior**
Impossible to use imagify after change the key

**Screenshots**

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by GeekPress** [comment]
Hi @madvik 

Sorry for the very late response.

For problems like that, please reach out to our support. You can do it easily from here: https://imagify.io/contact/

Regards
