### ISSUE TITLE
WebP image is x10 heavier than original JPG file!!!

### ISSUE THREAD

**Issue by Klemart3D** [wp-media/imagify-plugin#622]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version YES: v.1.10
- Used the search feature to ensure that the bug hasn’t been reported before : Is there #392 but not really fixed

**Describe the bug**
Imagify converts images to WebP which are x10 heavier than original file.

**To Reproduce**
1. Go to Media library
2. Add a new picture and wait for "optimization"
4. See very voluminous optimize file size, "gain" is negative (like for hundreds of pictures)
5. Now my space disk is full because of this "optimization" plugin that I paid for…

**Expected behavior**
Don't convert an image if webp format is bigger than original uploaded file or add an option to choose for that.

**Screenshots**
![webp](https://user-images.githubusercontent.com/7419525/136590175-f386ce6c-02a5-4d8e-ac21-9774bc02f884.jpg)

**Additional context**

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by Klemart3D** [comment]
This may be can help: https://github.com/wp-media/imagify-helpers/tree/master/webp/imagify-prevent-larger-webp

**Comment by markonikolic985** [comment]
Hey @Klemart3D 

Thanks for sharing this. We already have the opened issue for this [#510 ](https://github.com/wp-media/imagify-plugin/issues/510), so I am closing this one as we can follow the progress on #510.

We are considering solutions for this and should be able to find a proper one in the near future.
