### ISSUE TITLE
Improved Error Message For Unknown Errors

### ISSUE THREAD

**Issue by joejoe04** [wp-media/imagify-plugin#637]
Looking at [this code snippet](https://github.com/wp-media/imagify-plugin/blob/5971929e9842066e1351704ce14f25c5f31a7180/inc/functions/api.php#L181) we send the error message to users, "An unknown error has occurred." if optimization fails but the server returns no error message.

![image](https://user-images.githubusercontent.com/45705494/145471516-4afc3ace-f4a5-450c-a0da-13e9ff39c81b.png)

We offer the same solutions for these errors (increase WP memory, increase PHP timeout, use GD, etc) as for cURL Error 28 / timeout issues, and I think it could be helpful to send an error message to the user other than “Unknown error occurred.” Something like the following could be more useful.

![image](https://user-images.githubusercontent.com/45705494/145600789-91b1970f-bc14-4c37-a49c-8755a869ab6a.png)

Which we could link to the Optimization is Stuck page and provide a section in there about Unknown Errors. Or we could link to a separate page, whatever would be best.

`<td colspan="5">An unknown error occurred: <a href="https://imagify.io/documentation/optimization-is-stuck/" rel="noopener" target="_blank">More info and possible solutions</a></td>`

**Comment by GeekPress** [comment]
Please note the change will have to be done only on the Media Library page. The Bulk Optimization won't contain the details anymore started 2.1.
