### ISSUE TITLE
Keep EXIF Data in thumbnails too after optimization

### ISSUE THREAD

**Issue by joejoe04** [wp-media/imagify-plugin#659]
**Describe the bug**
If a user has the `Keep all EXIF data from your images` option enabled, after optimization, the EXIF data is missing from the thumbnails.

**To Reproduce**
1. Enable the `Keep all EXIF data from your images` option in the Imagify plugin settings page
2. Disable at least one thumbnail size from optimization in the `Files Optimization` section
3. Upload a test image with EXIF data and optimize it
4. You should notice that the original image (or -scaled version if applicable) retains the EXIF data after optimization, but all the thumbnails that were optimized no longer have the EXIF data
5. We can also see the EXIF data remains in the thumbnail size(s) excluded from optimization, so we know the EXIF data is there when WordPress creates the thumbs on upload, but is removed after optimization.

**Expected behavior**
EXIF data should be preserved for all images (original and thumbs) after optimization.

**Additional context**
Here is the user comment that brought this to our attention:
https://wordpress.org/support/topic/metadata-gets-removed-for-thumbnails/

• This is also somewhat related to [Issue #614](https://github.com/wp-media/imagify-plugin/issues/614)

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by MatzeKitt** [comment]
If you need further information, just ping me. 🙂
