### ISSUE TITLE
Rename « Account  Type » with « API Key » & remove subscription name on settings & bulk optimization pages

### ISSUE THREAD

**Issue by markonikolic985** [wp-media/imagify-plugin#662]
In Imagify Settings page, where the API Key card is located, the "Starter" plan label does not change when users subscribe to a paid plan, which might be confusing.

![image](https://user-images.githubusercontent.com/7384779/167134613-3cccf4fe-98e1-4dc5-8d5d-dd30d35d05e3.png)

This part is called from [here](https://github.com/wp-media/imagify-plugin/blob/5971929e9842066e1351704ce14f25c5f31a7180/views/part-settings-account.php#L72).

**Comment by GeekPress** [comment]
@Tabrisrp I have the same issue. After switching to Infinite plan, the plugin is still displaying the Starter plan. Don't we have a transient or something which keeps the previous status of the plan?

**Comment by remyperona** [comment]
Yes this section is using data coming from a transient, while the one in the admin bar is making an AJAX request with no cache

**Comment by GeekPress** [comment]
After discussing with Agathe, we validated removing the « Starter/Growth/Infinite » value in the « Account Type » section, and renaming it « API Key ».

This will need to change in the settings and Bulk Optimization pages.
