### ISSUE TITLE
Smart compression in Imagify plugin

### ISSUE THREAD

**Issue by piotrbak** [wp-media/imagify-plugin#663]
**Is your feature request related to a problem? Please describe.**
Imagify App can handle the smart compression, we need to update plugin to be fully compatible with it.

**Describe the solution you'd like**
Epic card can be found here:
https://docs.google.com/document/d/1NcaJc9xcJepH4ErJ4--Y4WNmUEN6Jym1E8ucgWi9ik4/edit?usp=sharing

**Comment by remyperona** [comment]
### Removal of the exif option
- update the related section in `README.md`
- update the related section in `readme.txt`

`classes/context/AbstractContext`
- remove the `$can_keep_exif` property and `can_keep_exif()` method

`classes/context/ContextInterface`
- remove the `can_keep_exif()` method

`classes/context/CustomFolders`
- remove the `can_keep_exif()` method

`classes/context/Noop`
- remove the `can_keep_exif()` method

`classes/context/WP`
- remove the `can_keep_exif()` method

`classes/Optimization/File`
- remove the `keep_exif` key from the arrays in `optimize()`, `$args` and `$data`

`classes/Optimization/Process/AbstractProcess`
- remove the `keep_exif` key from the arguments passed to the `optimize()` method
- remove the `can_keep_exif()` method

`inc/3rd-party/nextgen-gallery/classes/Context/NGG`
- remove the `can_keep_exif` property

`inc/classes/class-imagify-options`
- remove references to the `exif` option

`inc/functions/common`
- remove the `exif` case in `imagify_get_external_url()`

`views/page-settings.php`
- remove the keep exif setting section

**Comment by remyperona** [comment]
### Removal of the optimization level option

`views/page-settings.php`
- remove the optimization level setting section

Following points need more details:

`inc/functions/admin-ui.php`
- update `get_imagify_attachment_reoptimize_link()` to return the link to `smart` or `lossless` compression depending on the current level

`inc/classes/class-imagify-files-list-table.php`
- update `reoptimize_buttons()` method to return the link to `smart` or `lossless` compression depending on the current level

**Comment by remyperona** [comment]
### Lossless and Smart choices
`views/button/re-optimize.php`
- Replace the 3 existing level labels with the lossless and smart labels instead

`views/part-bulk-optimization-table-row-folder-type.php`

`inc/functions/common.php`
- Replace the 3 existing levels with the lossless and smart labels instead

**Comment by GeekPress** [comment]
QA done, I have only 2 feedbacks:

1.
> If a user had Normal selected as optimization level, the new images will be optimized by using the Smart Compresion with 2.0.

@Tabrisrp This acceptance criteria is failing. After updating to the new version, new images are still optimized using the Lossless compression instead of the Smart compression.

2. In the Bulk Optimization table, we will remove the choice between switching to Normal & Smart compression.

**Comment by GeekPress** [comment]
I tested the last version. QA is finished, and everything is good.
