### ISSUE TITLE
Compatibility with PHP 8 syntax

### ISSUE THREAD

**Issue by ionikol** [wp-media/imagify-plugin#671]
This issue is created according to [this ticket](https://secure.helpscout.net/conversation/1915452165/347603?folderId=3572901) where the user’s host has disabled the set_time_limit() function and that creates an issue with Bulk optimization(since the set_time_limit() function is one of the server requirements for Imagify to work)

Info from the logs:
PHP Fatal error: Uncaught Error: Call to undefined function Imagify\\Bulk\\set_time_limit()

When switched the PHP version from 8.0 to 7.4 the issue disappears.

I have contacted Ahmed and we may need to show admin_notice in case we found that this function isn't there so the user may increase the maximum execution time by himself in php.ini

**Comment by benoitchantre** [comment]
@ionikol Any progress on this?
