### ISSUE TITLE
Re-introduce Lossless Compression option

### ISSUE THREAD

**Issue by GeekPress** [wp-media/imagify-plugin#686]
## What are we proposing to do? 
With this update, we want to add an option to select lossless compression and not force the usage of Smart compression by default.

All details: https://docs.google.com/document/d/1pVuDP87-L-O1uH_oV2eqmfJDBrCLZ9drtFWqrx8WZoE/edit?usp=sharing

**Comment by remyperona** [comment]
### Scope a solution ✅ 
#### `Imagify_Options`
- Add new option `lossless` with default value 0 in `$default_values` array, and `$reset_values` array.
- Add case `lossless` to `sanitize_and_validate_value()`

#### `MediaOptimization::sanitize_optimization_level()`
- Update the method to account for the new lossless option

#### `Process::sanitize_optimization_level()`
- Update the method to account for the new lossless option

#### `views/page-settings.php`
- Add new checkbox setting for lossless compression option

#### `views/part-bulk-optimization-table-row-folder-type.php`
- Add back level selector

#### `views/part-bulk-optimization-table.php`
- Add back cell title

### Estimate the effort ✅
effort `[S]`
