### ISSUE TITLE
Optimization often fails after v2.1 update

### ISSUE THREAD

**Issue by validatorhq** [wp-media/imagify-plugin#707]
**Describe the bug**
We have more than usual reports of failed optimization process (bulk and individual). Our standard [debugging process](https://imagify.io/documentation/optimization-is-stuck/) fails and there is no any specific error reported.

The "Optimize" button simply comes back to processed image.

Checking at the Action Scheduler page does not help, as there is no visible error.

**To Reproduce**
It's a bit hard to reproduce, I was not able to do it on 3 of my test sites.

**Expected behavior**
Optimization should be completed, or at least we should get a visible error report so we could act further.

**Screenshots**
<img width="1220" alt="Screenshot 2022-12-28 at 16 59 11" src="https://user-images.githubusercontent.com/121193674/209917988-d3a26652-70b3-4f8b-a5eb-1305ed3f4390.png">

<img width="1257" alt="Screenshot 2022-12-29 at 05 51 31" src="https://user-images.githubusercontent.com/121193674/209918104-04a5d536-2e3e-4135-b7f9-687b356303ae.png">

<img width="1226" alt="Screenshot 2022-12-28 at 16 58 59" src="https://user-images.githubusercontent.com/121193674/209918305-356aa928-ceba-4715-b51d-21fdf6679957.png">

Even though it says the action is complete, no image was optimized.

**Additional context**
The background process run and it is spinning when we check the Bulk optimization page, but if we go back to the Media Library, no image is processed (all of them in this case were whether optimized or have "Optimize" button).

**Comment by piotrbak** [comment]
@validatorhq To move forward there we need to have access to some sample sites that are experiencing the issue.

**Comment by markonikolic985** [comment]
@piotrbak We have a couple of tickets with WP Admin access, waiting for SFTP access as well.

You can check tickets under `img gh 707` tag [here](https://secure.helpscout.net/search/?query=tag%3Aimg%20gh%20707) and see if there is the update from customers with SFTP access.
