### ISSUE TITLE
Generate missing WebP versions tool counts also WebP images

### ISSUE THREAD

**Issue by ionikol** [wp-media/imagify-plugin#713]
**Describe the bug**
After the update on v2.1.1 when an image in WebP format is directly uploaded on Media Library and gets optimized then the "Generate missing WebP versions" tool counts it as an optimized image without WebP version created.

**To Reproduce**
1. Go to Media > Library
2. Upload an image in WebP format
3. Optimize the image 
4. Then check through Settings > Imagify that the image counted as it has no WebP version created.

<img width="951" alt="Screenshot 2023-02-13 at 11 35 53" src="https://user-images.githubusercontent.com/59447333/218423626-ee5be173-d0b9-419a-8294-eeff2c348c2f.png">

**Expected behavior**
It should not be counted to the "Generate missing WebP versions" tool.

**Additional context**
https://secure.helpscout.net/conversation/2144254976/398940?folderId=3572901
https://secure.helpscout.net/conversation/2147413903/399460?folderId=676702
https://wp-media.slack.com/archives/C5S1X8WBY/p1676038727693139

**Backlog Grooming (for WP Media dev team use only)**
- [ ] Reproduce the problem
- [ ] Identify the root cause
- [ ] Scope a solution
- [ ] Estimate the effort

**Comment by raabmar** [comment]
I just want to add one thing here - the "Generate Missing WebP Version" gets stuck forever. I think that might be related.
<img width="810" alt="image" src="https://user-images.githubusercontent.com/15885290/219661909-75da449a-3ce3-4749-9bee-2b0ddfe687ef.png">

**Comment by agenceKanvas** [comment]
I think I have the same problem. 8000 to generate but stuck at 0.
I have this error, probably related : 
`PHP Fatal error:  Uncaught Exception: Serialization of 'CURLFile' is not allowed in /home/marsbetausr/www/wp-content/plugins/imagify-tools/functions/common.php:101\nStack trace:\n#0 /home/marsbetausr/www/wp-content/plugins/imagify-tools/functions/common.php(101): serialize()\n#1 /home/marsbetausr/www/wp-content/plugins/imagify-tools/classes/class-imgt-logs.php(653): imagify_tools_compress_data()\n#2 /home/marsbetausr/www/wp-content/plugins/imagify-tools/classes/class-imgt-logs.php(609): IMGT_Logs::insert_log()\n#3 /home/marsbetausr/www/wp-content/plugins/imagify-tools/classes/class-imgt-logs.php(520): IMGT_Logs->save_logs()\n#4 /home/marsbetausr/www/wp-includes/class-wp-hook.php(308): IMGT_Logs->save_current_logs()\n#5 /home/marsbetausr/www/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()\n#6 /home/marsbetausr/www/wp-includes/plugin.php(517): WP_Hook->do_action()\n#7 /home/marsbetausr/www/wp-includes/load.php(1124): do_action()\n#8 [internal function]: shutdown_action_hook()\n#9 {main}\n  thrown in /home/marsbetausr/www/wp-content/plugins/imagify-tools/functions/common.php on line 101, referer: https://marsactu.fr/wp-admin/admin-ajax.php?action=imagify_optimize_media&nonce=5d18108bc`

I've installed the helper (I found version 1.1.2) and everything is ok. 

Oh and I run php 8.1, last version of everything on WP side

**Comment by ligerio-repo** [comment]
@agenceKanvas Hi, what is the Helper you reference to ? It's always stuck

**Comment by tbba** [comment]
I also have the "generate missing nextgen versions stalling",now for AVIV images. Tested on serval instances. It is a relatively new phenomena, I remember it worked before. Generating WEBP works.

**Comment by tbba** [comment]
Still not fixed. Any update? What "helper"?

**Comment by DevArounder** [comment]
Imagify Deokumentation brought me here: https://imagify.io/documentation/generate-missing-webp-versions-feature-is-stuck/ but again, there is no solution to the problem and has been for over 2 years.

Problem still exists today. I sent a ticket to support at the weekend. Still unanswered today.

**Comment by extremeleadprogram** [comment]
I have a lot of images on a site - 95,381.

Initially, I had imagify generate and serve .webp images. I switched this to .avif and am having it regenerate the images but it keeps getting stuck. It will generate a few and quit.

We need a fix to this problem... anyone find a work around?

I've tried a few WP Cli commands with no luck...

**Comment by vonwalland** [comment]
I am running into this issue still as well.
