### ISSUE TITLE
Update the account status notification in the toolbar menu

### ISSUE THREAD

**Issue by marija-nikolic** [wp-media/imagify-plugin#727]
We would like to update copy and color for the part of the account status notification in the toolbar menu (red box), for the users who are <= 20% of the unconsumed quota.

Details are provided [here](https://docs.google.com/document/d/18dnmVYjUaNk5T1cGDcozPrSPg6UeqhcqnhaR_sUj1tQ/edit#).

**Comment by piotrbak** [comment]
Acceptance Criteria:
- **Promo section is not a part of this PR**
- When the user is less or equal to 20% of his quota, we'll update the banners.
- It's related to Free and Growth users only
- The `View my subscription` button will be removed when displaying this banner
- Copyright for Free and Growth users will be different and it's present in the document.
- The design and colors are available in the document
- Links for Free, Growth monthly and Growth Yearly will be different and they're present in the document
- The banner will be dismissible
- Once dismissed, the banner won't be displayed until the quota is restarted and going to 20% again (@marija-nikolic or should it be dismissed forever?)

**Comment by marija-nikolic** [comment]
> Acceptance Criteria:
> 
> * **Promo section is not a part of this PR**
> * When the user is less or equal to 20% of his quota, we'll update the banners.
> * It's related to Free and Growth users only
> * The `View my subscription` button will be removed when displaying this banner
> * Copyright for Free and Growth users will be different and it's present in the document.
> * The design and colors are available in the document
> * Links for Free, Growth monthly and Growth Yearly will be different and they're present in the document
> * The banner will be dismissible
> * Once dismissed, the banner won't be displayed until the quota is restarted and going to 20% again (@marija-nikolic or should it be dismissed forever?)

Not forever. As you said until the quota is restarted and going to 20% again.

**Comment by remyperona** [comment]
### Scope a solution ✅ 
The method managing the display of this section is currently in `Imagify_Admin_Ajax_Post:imagify_get_admin_bar_profile_callback()`.

Looking at what is needed to happen, I think the better approach will be to extract that method to its own class, and create views for it too (right now the HTML is directly in the method).

In addition, we will need to:
- Do a check for the user current plan
- Remove the view my subscription link
- Add a the button to dismiss the banner
- Add a check in the code to verify if the banner was dismissed
- Add a reset of the dismiss if the quota is above 20% again
- Update the CSS

### Estimate the effort ✅
effort [M]

**Comment by Miraeld** [comment]
Looks fine to me
