### ISSUE TITLE
Display an upsell banner for the users out of the quota

### ISSUE THREAD

**Issue by marija-nikolic** [wp-media/imagify-plugin#728]
We would like to remove the existing top banner and display an upsell banner to offer users who are out of the quota to upgrade their plan.

Details are provided [here](https://docs.google.com/document/d/1crsUJVfNdKSeNOkKUAnrnv8wGEiLeXlTw79--bjaU70/edit#).

**Comment by piotrbak** [comment]
Acceptance Criteria:
- **Promo part will not be implemented in this PR**
- Top banner `running out of quota` will be removed
- When the user is out of quota, we'll display a banner on the right sidebar. In the place of the current view in the Bulk Optimization and Settings tabs (present in the document)
- Copywriting and links will be different depending on what's the license of the current user: 1. Free 2. Growth Monthly 3. Growth Yearly (details in the doc)
- After clicking on the button the customer will be brought to the Imagify Checkout URL

**Comment by remyperona** [comment]
### Scope a solution ✅ 
- Remove the almost over quota method in the Notices class
- Remove the related view
- Add a check for the user current plan
- Update the page-bulk and part-settings-account view with the new content
- Update the CSS

### Estimate the effort ✅
Effort [S]

**Comment by Miraeld** [comment]
Looks fine to me
