### ISSUE TITLE
Chart.js version 2.7.1 vulnerability

### ISSUE THREAD

**Issue by stathopoulosgeorge** [wp-media/imagify-plugin#742]
**Describe the bug**

We received a WordPress.org [ticket](https://wordpress.org/support/topic/chart-js-pen-test-results/) for Imagify, regarding the current version of Chart.js used (2.7.1 which was released 6 years ago).

The user has done a web application penetration test which revealed a Prototype Pollution vulnerability, rated as critical on the NVD database.

[Ticket]: https://wordpress.org/support/topic/chart-js-pen-test-results/
[File location]: Imagify > assets > js > chart.js
[Vulnerability database]: https://security.snyk.io/vuln/SNYK-JS-CHARTJS-1018716
[Slack thread]: https://wp-media.slack.com/archives/C056ZJMHG0P/p1690190179414269

**Comment by CrochetFeve0251** [comment]
## Scope a solution

To update chart.js we will have to download the new version from chart.js here: https://cdn.jsdelivr.net/npm/chart.js

Then change the content from the file [`imagify/assets/js/chart.js](https://github.com/wp-media/imagify-plugin/blob/develop/assets/js/chart.js)` to the new content.

While doing so we need to be careful to keep the 3 lines:
https://github.com/wp-media/imagify-plugin/blob/cfe6f77940b520500d8ef00be18b4ee24167b49f/assets/js/chart.js#L10
https://github.com/wp-media/imagify-plugin/blob/cfe6f77940b520500d8ef00be18b4ee24167b49f/assets/js/chart.js#L718C1-L718C31
https://github.com/wp-media/imagify-plugin/blob/cfe6f77940b520500d8ef00be18b4ee24167b49f/assets/js/chart.js#L1736

Then compile the js again and check for potential issues.

If the time allows it we should refactor it by adding chart.js into the node dependencies and import it inside the chart.js file.
Then setup the `window.imagify` using the values exported by chartjs.

## Estimate effort
Effort `S`

PS: S for the high potential of issue cause we are passing from 2.xx to 4.xx

**Comment by Miraeld** [comment]
Seems good to me, 
Like you said, we need to pay attention to potential issues that will be caused by the major version upgrade.
