### ISSUE TITLE
Imagify plugin banners are not styled

### ISSUE THREAD

**Issue by piotrbak** [wp-media/imagify-plugin#765]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
In the 2.1.3 version we changed the way how banners are updated. However, the styling was not deployed from develop to the live version of the plugin.

**Expected behavior**
Styling should be present as desscribed in the following issues:
https://github.com/wp-media/imagify-plugin/issues/727
https://github.com/wp-media/imagify-plugin/issues/728

**Screenshots**
![image](https://github.com/wp-media/imagify-plugin/assets/26767037/6d3b360f-9618-4207-8371-301c7e66de2c)
![image](https://github.com/wp-media/imagify-plugin/assets/26767037/847b97c1-4412-4454-8ebc-72ec101ab4a3)

**Acceptance Criteria (for WP Media team use only)**
1. Styling described in the original issues should be applied, it's present on the develop branch

**Comment by remyperona** [comment]
They are correctly displayed when using the unminified version of the CSS, but the minified version was not updated before releasing.

Running the grunt task to regenerate the minified files will fix this.
