### ISSUE TITLE
AVIF Support: settings page

### ISSUE THREAD

**Issue by remyperona** [wp-media/imagify-plugin#772]
#### In `views/part-settings-web.php`

- Update the title to `Next-gen image format`
- Update the WebP checkbox to Avif checkbox, with new option name, label, described
- Add the description for the option using the "imagify-info" class
- Add a separator between this option and the other part
- Update the label for the display option

#### In `views/part-settings-webp-missing-message.php`
- Update the label replacing WebP by Next-Gen

### Estimate the effort ✅
Effort [XS]

**Comment by Miraeld** [comment]
@Tabrisrp , Umm, when you say 
> Update the WebP checkbox to Avif checkbox, with new option name, label, described

Do you mean replacing WebP by AVIF or adding a checkbox for AVIF which would result in 2 times approximately the same form elements but with different name (WebP & AVIF)

**Comment by MathieuLamiot** [comment]
@Miraeld I think it is replacing and not adding a similar form. You can refer to the EPIC card with the product team's specifications: https://www.notion.so/wpmedia/AVIF-Imagify-Plugin-4a870cab6e0d4232a85962f0b4c1c63a?pvs=4#24bc7a3f47764c878aed0e64559f1752
The behavior will change a bit: if AVIF is checked, we generate AVIF. If it is not checked, we generate WebP.

(@piotrbak and @Tabrisrp for confirmation)

**Comment by MathieuLamiot** [comment]
Could be a nice first issue to keep for Opeyemi

**Comment by remyperona** [comment]
Indeed we are replacing the existing WebP option with a new one for AVIF

**Comment by Mai-Saad** [comment]
@Tabrisrp Shall this ticket includes updating the button name from `Generate Missing WEBP Versions` to `Generate Missing Next-Gen Images Versions` or it's the scope of another ticket?
Currently, it is still WEBP:
![Screenshot from 2024-01-12 16-00-58](https://github.com/wp-media/imagify-plugin/assets/76941962/10443f3f-bba4-4091-b99c-9fd71ba63440)
Another thing, if we check the AVIF options and saved, it will be automatically unchecked. Is this out of scope here?
