### ISSUE TITLE
AVIF support: media library view

### ISSUE THREAD

**Issue by remyperona** [wp-media/imagify-plugin#779]
#### In `inc/classes/class-imagify-admin-ajax-post.php`
- rename `imagify_generate_webp_versions` to `imagify_generate_nextgen_versions`
- rename `imagify_generate_webp_versions_callback()` to `imagify_generate_nextgen_versions_callback()`
- rename `generate_webp_versions()` to `generate_nextgen_versions()` and update the method to use method from the optimization process to generate all next-gen versions needed

- rename `imagify_delete_webp_versions` to `imagify_delete_nextgen_versions`
- rename `imagify_delete_webp_versions_callback()` to `imagify_delete_nextgen_versions_callback()`
- rename `delete_webp_versions()` to `delete_nextgen_versions()` and update the method to delete all next-gen versions existing

#### In `inc/classes/class-imagify-files-list-table`
- rename `generate_webp_versions_button()` to `generate_nextgen_versions_button()`

#### In `inc/functions/admin.php`
- Update `get_imagify_admin_url()`, update the cases for `'generate-webp-versions` and `delete-webp-versions` to `generate-nextgen-versions` and `delete-nextgen-versions`

### Estimate the effort ✅
Effort [S]

**Comment by Khadreal** [comment]
> update the method to use method from the optimization process to generate all next-gen versions needed

To clarify, we're changing the `webp` related methods name  to `nextgen` in Noop class and the interface

**Comment by remyperona** [comment]
Yes we should update in the process classes as well
