### ISSUE TITLE
Error is displayed when click 'Generate Missing Next-Gen Images Versions' while no optimization is selected

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/imagify-plugin#789]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => Avif commit: https://github.com/wp-media/imagify-plugin/commit/b396de27cda71d9b16e311a0f55f482bebf13380
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Error is displayed when clicking 'Generate Missing Next-Gen Images Versions'

**To Reproduce**
1. Fresh activation of Imagify
2. Click on 'Generate Missing Next-Gen Images Versions'

**Expected behavior**
WebP versions are generated while AVIF is not checked

**Screenshots**
![Screenshot from 2024-02-02 08-22-27](https://github.com/wp-media/imagify-plugin/assets/76941962/f693d969-68b6-41db-bf7b-e48f139b2717)

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming
- If AVIF is checked and we detect that there are missing AVIF images for optimized ones, we’ll create only AVIF versions for the images
- If AVIF is not checked, we’ll create only Webp versions for the images
- If filter is set to generate both AVIF/WebP, then both will be generated while AVIF option is checked
- WebP generation won't consume quota

**Comment by Mai-Saad** [comment]
While AVIF is enabled can see this
![Screenshot from 2024-02-05 12-17-33](https://github.com/wp-media/imagify-plugin/assets/76941962/cfaf705d-d8ad-4820-bdb8-7ea425b64035)

**Comment by Mai-Saad** [comment]
This error is there either AVIF enabled/disabled. @Tabrisrp can you please check? (tested on https://imagify.rocketlabsqa.ovh/) 
![Screenshot from 2024-02-23 04-31-11](https://github.com/wp-media/imagify-plugin/assets/76941962/4eebca53-3d42-4670-8d92-9de90679f4b8)

Note:
when used  clean local env, couldn't see the btn at all (even while having some images with the generate link in media library). Are you able to see it on clean local env? how?

**Comment by remyperona** [comment]
I updated the minified JS on the main branch, which was likely the issue here.

**Comment by Mai-Saad** [comment]
No error now.
note: on new clean sites, it's very hard to see the generate btn now in settings page
