### ISSUE TITLE
In media library New image size shall be that of AVIF|webP|optimized based on which exists

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/imagify-plugin#794]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => Avif commit: https://github.com/wp-media/imagify-plugin/commit/b396de27cda71d9b16e311a0f55f482bebf13380
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
The New image size is always the original image optimized size instead of the webP (as on trunk) or the AVIF. After discussion, with @piotrbak , agreed that we shall display the new size as the smallest size

**To Reproduce**
1. Enable the Avif
2. upload image
3. check the image in the media library => compare the new size to that in ftp, it will be the optimized image size, not the AVIF one although AVIF is smaller

**Expected behavior**
The smaller size of the optimized image shall be displayed in the media library as a new size

**Screenshots**
![Screenshot from 2024-02-02 12-50-19](https://github.com/wp-media/imagify-plugin/assets/76941962/5037a507-91f1-4982-a4cd-8b6d3c2696b5)

**Additional context**
- on trunk, if create webP is enabled, then we will display the webP size which is < original optimized image size (so sounds like regression on PR)

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming
- New size is always = smallest size version of image , either original optimized, .webP, or .AVIF based on which version is available

**Comment by piotrbak** [comment]
Hey @Tabrisrp Isn't 2.2.1 a correct milestone for this one?
