### ISSUE TITLE
Compare original vs optimized image isnot working probably

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/imagify-plugin#795]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => 2.1.3.1
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
1- When click compare original vs optimized in the images list, 'Yes' is there beside the optimized size
![Screenshot from 2024-02-02 15-28-04](https://github.com/wp-media/imagify-plugin/assets/76941962/5c99a9b1-2afb-471a-a8a8-8c8be42396db)
2- When click compare original vs optimized from edit image page, the original and optimized sizes are the same = approximated original size
![Screenshot from 2024-02-02 15-30-28](https://github.com/wp-media/imagify-plugin/assets/76941962/58341672-09f2-4df3-9e57-080910b16888)

**Expected behavior**
Size is similar in both views 1,2 where original != optimized size as long as the image is optimized

**Screenshots**

**Additional context**
- Original Size in the backup folder is 41.6K while in the media library list is 40.57K while in 2nd point above is 41K => Will leave this to @wp-media/productimagify to decide if further investigation/GH is needed about that
- Possible enhancement =>  here is to make both 1,2 have the same position for 'x'
- Possible enhancement => decrease the space between file size: value
- Same on AVIF branch

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
@Mai-Saad Is this a regression in the 2.2 branch?

**Comment by Mai-Saad** [comment]
@piotrbak it's already on 2.1.3.1 version (not related to AVIF)
