### ISSUE TITLE
1st activation of avif won't run automatically in the background

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/imagify-plugin#825]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => commit 324c4fa030cb3197aef071d09845184f0819fe9f
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When we enable AVIF for the 1st time after fresh activation, AVIF won't be automatically generated (reactivate avif will make the creation works automatically)

**To Reproduce**
1. install and activate imagify
2. upload some images (small, medium, big)
3. activate avif => (notice that bulk notice isnot displayed)
4. check media library => generate next-gen link displayed (nothing generated in background)

**Expected behavior**
Automatic creation of avif works even when activating the option for the 1st time

**Screenshots**
Video and sample images
[screen-capture (84).webm](https://github.com/wp-media/imagify-plugin/assets/76941962/9ab3200f-5ffd-4390-b21b-d07096072e49)
![download (33)](https://github.com/wp-media/imagify-plugin/assets/76941962/06c52734-f4e1-435c-abf3-97df5b93b6cd)
![file_example_JPG_100kB (1)](https://github.com/wp-media/imagify-plugin/assets/76941962/304c515a-a294-4bad-8acc-b59c0d7aff7d)
![mountain](https://github.com/wp-media/imagify-plugin/assets/76941962/36aab1b3-0937-4ddb-b575-7e377991140f)

**Additional context**
- Reactivate AVIF will work

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by MathieuLamiot** [comment]
We declare `maybe_generate_missing_nextgen` as a callback to `update_option_imagify_settings`. However, update_option_xxx hooks seem to only run when updating an option, not creating it. This is explained [here](https://wordpress.stackexchange.com/questions/330289/update-option-option-action-not-working-as-expected) and [here](https://developer.wordpress.org/reference/functions/update_option/#comment-2396), and can be seen in [WP Core code](https://developer.wordpress.org/reference/functions/update_option/).

I think we should declare `maybe_generate_missing_nextgen`  as a callback to [add_option_imagify_settings](https://developer.wordpress.org/reference/hooks/add_option_option/) as well

**Comment by MathieuLamiot** [comment]
Also, don't know if it is related:
@Tabrisrp I am not sure to understand the meaning of this line in `maybe_generate_missing_nextgen`

```
if ( isset( $old_value['convert_to_avif'] ) && isset( $value['convert_to_avif'] ) ) {
    return;
}
```

Don't we risk to bail out when both are set, but old value is set to 0, and new value to 1?

**Comment by MathieuLamiot** [comment]
discussing [here](https://wp-media.slack.com/archives/CUT7FLHF1/p1709286678369739)
