### ISSUE TITLE
Bulk optimization isnot working

### ISSUE THREAD

**Issue by Mai-Saad** [wp-media/imagify-plugin#830]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version => feature/avif and fix/826-prevent-reoptimize
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
When apply bulk optimization, message displayed that all images optimized although it isnot

**To Reproduce**
1. Fresh install/activation of feature/avif
2. upload some images (small, medium, large) => optimization is done
3. click restore original image for optimized image => next-gen removed and image(s) timestamp is updated
4. got to bulk optimization and click imagify all => message displayed that images are optimized
![Screenshot from 2024-02-29 10-37-34](https://github.com/wp-media/imagify-plugin/assets/76941962/5ac8f245-765f-45ee-81ca-e7a5c01d57ad)

**Expected behavior**
Bulk optimization is applied as same as on trunk (image timestamp/size is updated + next-gen is added as per enabled option)

**Screenshots**

when click bulk optimization and display that images already optimized
![Screenshot from 2024-02-29 10-51-05](https://github.com/wp-media/imagify-plugin/assets/76941962/8b646497-f094-4457-a8c4-9f9150f9f21b)

after manually click on the optimize 
![Screenshot from 2024-02-29 10-56-23](https://github.com/wp-media/imagify-plugin/assets/76941962/345ea367-418d-4e82-adfe-b45d414aec68)

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by piotrbak** [comment]
@Mai-Saad Is it happening only with the 3rd step `click restore original image for optimized image`? What about the images that were uploaded before but not yet optimised? (is it a regression?)

**Comment by Mai-Saad** [comment]
> Is it happening only with the 3rd step click restore original image for optimized image? What about the images that were uploaded before but not yet optimized?(is it a regression?)

@piotrbak The same is happening with images uploaded before activating imagify. and yes it is regression.

**Comment by piotrbak** [comment]
@Khadreal Were you able to find the root cause?

**Comment by Khadreal** [comment]
> @Khadreal Were you able to find the root cause?

Not yet..still on it
