### ISSUE TITLE
Bulk optimization - percentage optimization indicator jumps inconsistently during the process

### ISSUE THREAD

**Issue by markonikolic985** [wp-media/imagify-plugin#840]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
Testing v2.2 alpha, we noticed some inconsistencies during the bulk optimization process.

In the v2.1 the Bulk optimization works the way data is updated when image is optimized (% and number of optimized images) one by one (image and %), like this - https://capture.dropbox.com/726omrg388oYIvbf

However, in the v2.2 it does not update, but jumps from 0% to 50% or so, as well as the number of original images optimized by Imagify. 

Also, in another test, the number of optimized images went down and the percentage indicator was gone (when checked in the Media Library, optimzation was still running). Check this screenrecoed - https://capture.dropbox.com/W7I1XZogDscBUXw2

**Note:** At some moment, Imagif'em all button will stop spinning, but when you go to the Media Library, optimization is still running for many images. This particular problem already has its' own issue in [#756 ](https://github.com/wp-media/imagify-plugin/issues/756).

**To Reproduce**

1. Make sure you use v2.2
2. Go to the Bulk optimization page
3. Click on "Imagif'em All" button
4. Wait for optimization to start.
5. Check the number of optimized images and percentage indicator
6. Percentage will jump from 0-x% instead going one by one. The number of original optimized images will change accordingly

**Expected behavior**
Percentage indicator should show the progress one % by one, as it's the case in versions prior to v2.2, as well as the number of original images optimized by Imagify.

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by Mai-Saad** [comment]
fixed on https://github.com/wp-media/imagify-plugin/pull/842

**Comment by remyperona** [comment]
We can close this one?
