### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by jbma** [wp-media/imagify-plugin#85]
It looks like sometime $file_path is not working correctly and not returning the correct path

cf : https://secure.helpscout.net/conversation/378173418/41981/?folderId=676703

**Comment by Screenfeed** [comment]
Falls here: https://github.com/wp-media/imagify-plugin/blob/master/inc/functions/process.php#L57
`$file_path` is relative instead of being absolute.

**Comment by Screenfeed** [comment]
This bug doesn't come from Imagify, but from another plugin that messes with `wp_get_upload_dir()`, which is used in `get_attached_file()`: the plugin filters `'upload_dir'`, and to be concise, the `'error'` key becomes an empty string instead of a boolean false.

**Comment by Screenfeed** [comment]
OK, let's get dirty by adding a compat' file that will remove this plugin's filter.

**Comment by Screenfeed** [comment]
Related to the bug: https://codecanyon.net/item/wordpress-live-chat-plugin/3952877/comments?page=60&filter=all#comment_15770104
