### ISSUE TITLE
After updating to 2.2 WP Rocket's WebP addon doesn't detect Imagify as a WebP compatible plugin

### ISSUE THREAD

**Issue by alfonso100** [wp-media/imagify-plugin#850]
**Before submitting an issue please check that you’ve completed the following steps:**
yes - Made sure you’re on the latest version
yes - Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
After updating to 2.2 WP Rocket's WebP addon doesn't detect Imagify as a WebP plugin anymore

**To Reproduce**
1. Update Imagify to 2.2
2. On WP Rocket, go to the WebP addon
3. See the message:  `We have not detected any compatible WebP plugin!`

**Expected behavior**
we should detect Imagify as a WebP compatible plugin

**Screenshots**
![image](https://github.com/wp-media/imagify-plugin/assets/229406/df65f15b-c160-4bf3-bf7f-e5b94c858758)

**Additional context**
ticket https://secure.helpscout.net/conversation/2533421582/479330?folderId=273761

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by MathieuLamiot** [comment]
**Status update / summary:**

There are two aspects to be dealt with separately:

Case 1:
- When using Imagify 2.2, WP Rocket 3.15.10+ must correctly adapt the WebP compatibility display. to do this, WP Rocket must take into account the new setting names of Imagify. This is to be dealt with here: https://github.com/wp-media/wp-rocket/issues/6468 for WP Rocket 3.15.10.

Case 2:
- When using Imagify 2.2+, versions of WP Rocket 3.15.9 and before must correctly adapt the WebP compatibility display. To do this, Imagify plugin must maintain the old option display_webp / convert_to_webp appropriately. This part would be handled here: https://github.com/wp-media/imagify-plugin/issues/850

@piotrbak, can I let you see the prioritiy for case 2? (this issue) Thanks

**Comment by piotrbak** [comment]
@MathieuLamiot I think we could close this issue and leave only this one opened. What do you think?
https://github.com/wp-media/wp-rocket/issues/6468

**Comment by MathieuLamiot** [comment]
@piotrbak There are 2 issues to fix in 2 different places. One in Imagify, the other in WP Rocket.
Unless you decide not to fix case 2, we should keep this issue open.

Update from Piotr [here](https://wp-media.slack.com/archives/CUT7FLHF1/p1710158943075759?thread_ts=1710122401.117489&cid=CUT7FLHF1): _If the effort here is more than [XS] we could close the issue, 1st scenario is the priority. We'd ask customers to update both plugins._

**Comment by remyperona** [comment]
Isn't case 2 fixed by the update done in 2.2.0.1?

**Comment by MathieuLamiot** [comment]
That's the question raised [here](https://wp-media.slack.com/archives/CUT7FLHF1/p1710158716818179?thread_ts=1710122401.117489&cid=CUT7FLHF1). Maybe, I don't know. It needs to be checked. What I am worried about is that we brought back `display_webp` option but do we keep its value updated?

**Comment by remyperona** [comment]
It won't be updated anymore, so is the expectation to keep it updated based on convert to AVIF enabled, and the filter?

**Comment by MathieuLamiot** [comment]
The requirement is that with WP Rocket 3.15.9 and Imagify 2.2.0.1+, the 3rd party WebP display must be accurate.
That's the only way I see to keep backward compatibility with WP Rocket 3.15.9 and before ; otherwise the 3rd-party display won't be correct ; right?
As @piotrbak mentioned, if it's more than [XS] (and I would add, if it complicated the codebase too much), we will discard this issue.

**Comment by MathieuLamiot** [comment]
Re-opening for:
- Fix CI
- Fix the warning (if easy to fix): https://github.com/wp-media/wp-rocket/pull/6469#issuecomment-1994164794
