### ISSUE TITLE
Update the 2.2.2 Imagify branch

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/imagify-plugin#881]
1. We should add 0.5 opacity to the greyed out block to make it lighter when the filter is used
2. The Read More button should be underlined
3. The Read More button should link to the: https://imagify.io/documentation/how-to-use-the-next-gen-image-format-filter/

**Comment by piotrbak** [comment]
There's further feedback:
1. We should wrap the filter name inside `<code>` `</code>`
2. We should add the following CSS when the filter is used:
```
background: #ccc;
cursor: not-allowed;
color: #999;
```

Sorry for coming back with this.
