### ISSUE TITLE
Create a New Block in Imagify

### ISSUE THREAD

**Issue by Agathemed** [wp-media/imagify-plugin#895]
Description and assets available [here](https://docs.google.com/document/d/1LKH9s66lEYYveBus5imefMyuWGx1mnPUAHHogj9GO80/edit#heading=h.wmwupfxny905).

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
- First, we need to update this [section](https://github.com/wp-media/imagify-plugin/blob/56b4c97f0d719e850ec3001cde6d7230c9724157/views/page-settings.php#L104) content to fit with the description and mockup provided above.
- Next for each of the plugins stated, we need to check first if they are:
  - Installed: Check if there's a related path in the plugins directory for the said plugin.
  - Activated: Check that plugin is activated, we can do this using `is_plugin_active`
- If plugin is not active:
  - Install plugin using the `Plugin_Upgrader` class with the `install` method passing the plugin url.
  - Finally activate plugin using the `activate_plugin` function

We will need to create a class to manage this actions, this should be in the event driven architecture(EDA) that we already introduced

### Estimate the effort ✅
[M]

@Agathemed I do have a question, we have WP Rocket ad right now on imagify though with an option to dismiss. Should that be removed in favour of this new UI?
![Image](https://github.com/user-attachments/assets/8d8a1542-3f36-433a-a1fa-ea9d27f1c572)

**Comment by Miraeld** [comment]
Looks good to me, could be nice to get the answer from @wp-media/marketing before starting work on it as @jeawhanlee did ask a question. It would avoid back and forth if the answer is positive.

**Comment by Agathemed** [comment]
@jeawhanlee No change on the WP Rocket banner for now. Thx

**Comment by hanna-meda** [comment]
@wp-media/marketing, The updates are now complete and ready for your attention. Thank you!

**Comment by Agathemed** [comment]
How can we take a look at the updates, please?

**Comment by hanna-meda** [comment]
Hello @Agathemed, 

Sorry, I hadn't thought to provide you with a test site earlier. Here is one prepared for you with the latest changes: [test site link](https://simple.rocketlabsqa.ovh/wp-admin) (credentials in Bitwarden).

**Comment by Agathemed** [comment]
Why is Imagify removed from the menu here? [Image](https://github.com/user-attachments/assets/550111ad-7fb6-42b0-8e4f-ff323c47efbb)

**Comment by hanna-meda** [comment]
I’m sorry for the back and forth. I noticed another small fix needed for the “GET IT NOW” CTA from WP Rocket: the link currently opens in the same tab, but it should open in a new tab, as it does for all other “Learn More” links. I’ll update the PR with this fix and let you know as soon as it’s ready.

**Comment by hanna-meda** [comment]
@Agathemed, everything is ready now. Please check on this other [site](https://rocketlabsqa.ovh/wp-admin) (credentials in Bitwarden), as the first one provided did not meet the PHP version required for some of our plugins.

**Comment by Agathemed** [comment]
Perfect! 👌
