### ISSUE TITLE
Conflict with gravity forms noconflict mode

### ISSUE THREAD

**Issue by wordpressfan** [wp-media/imagify-plugin#919]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version **Yes**
- Used the search feature to ensure that the bug hasn’t been reported before **Yes**

**Describe the bug**

When gravity forms noconflict mode is enabled, the imagify pricing modal is showing on the page without any styling.

**To Reproduce**
1. Install and activate gravity forms
2. Install and activate imagify plugin
3. Go to gravity forms settings page from the admin menu
4. Enable no conflict mode and save the form by clicking on Save Changes button
5. You will see the modal in the footer without any styling.

**Expected behavior**
It should behave correctly and hide the modal by default.

**Screenshots**

![Image](https://github.com/user-attachments/assets/984cb2d1-6984-4ce7-9ebc-93870cd6d36b)

**Additional context**

Slack discussion: https://wp-media.slack.com/archives/C045P1RA2/p1731310030013799

**Possible solutions:**

1. Insert inline CSS to hide the modal `style="display: none;"`
2. Use the following filters to add our styles/scripts into no conflict mode:

https://docs.gravityforms.com/gform_noconflict_scripts/
https://docs.gravityforms.com/gform_noconflict_styles/

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by saranshj4** [comment]
https://secure.helpscout.net/conversation/2759170188/522428/
https://secure.helpscout.net/conversation/2757655775/522142/
https://secure.helpscout.net/conversation/2758516745/522301/
https://secure.helpscout.net/conversation/2758064944/522219/

**Comment by MathieuLamiot** [comment]
[dev-team-escalation](https://wp-media.slack.com/archives/C056ZJMHG0P/p1731939626561959) to consider as well for the fix.

**Comment by Khadreal** [comment]
The PR created [here](https://github.com/wp-media/imagify-plugin/pull/924) fixed this but needs to be tested

**Comment by Mai-Saad** [comment]
Acceptance criteria:
- The banner isnot displayed inside gravity form settings while no conflict is on/off
- The upgrade button is working in admin bar (green banner), settings page and bulk optimization (for starter with remaining quota > 20%)
- The red banner displayed correctly when the remaining quota is < = 20% (upgrade links are working in admin bar, settings, bulk optimization)

@piotrbak what do you think?

**Comment by Mai-Saad** [comment]
Related test plan https://wpmediaqa.testrail.io/index.php?/runs/view/939&group_by=cases:section_id&group_order=asc
