### ISSUE TITLE
Reduce the number of calls to Imagify API users/me

### ISSUE THREAD

**Issue by MathieuLamiot** [wp-media/imagify-plugin#923]
**Context**
2.2.3 introduced a call for user data on all admin pages. As a result, we perform calls to the Imagify API users/me much more often. However, the data from the API is not directly required on all admin pages, but rather on bulk & setting pages, as well as when opening the Imagify admin bar (which is on all admin pages).
A mitigation has been set with a response cache of 5 minutes with the transient `imagify_user_cache`. However, the number of calls to the API remains high overall, and further increasing the transient TTL would disrupt the freshness of the data as explained [here](https://wp-media.slack.com/archives/CU0F6EGQ1/p1731446970319949).

**Expected behavior**
Highly reduce the number of calls to Imagify API users/me overall.
Ideally, as explained here, we should perform calls to the API only when really needed (bulk & settings pages, or when hovering the Imagify admin bar) and combine this with some caching for a short amount of time (as already done).
If this is not possible, other alternatives can be considered such as a longer cache time but providing a refresh button.
See the discussion [here](https://wp-media.slack.com/archives/CU0F6EGQ1/p1731446970319949)

**Acceptance Criteria**
The main acceptance criteria is that the number of calls to the Imagify App must be reduced overall. Exact ACs will depend on the approach selected (request only when needed or longer cache + refresh).

For "request only when needed":
- With Imagify activated, when I clear the transients and browse admin pages (excluding bulk, settings) and not hovering the Imagify admin bar, no requests to users/me are done.
- When hovering the Imagify admin bar, after a short amount of time, I can see my license type, my quota consumed and possibly the upsell banner (see [upsell banner conditions](https://github.com/wp-media/imagify-plugin/issues/898))
- Upsell block behaves as expected on Bulk & Setting pages (see https://github.com/wp-media/imagify-plugin/issues/898)

For "longer cach + refresh".
- With Imagify activated, when I clear the transients and browse admin pages for x minutes, I can see one request to users/me at first and then not anymore. x should be the cache duration (typically > 10 minutes).
- In the Imagify admin bar, there is a refresh icon. When I have a free or growth plan and users/me response cached in transient, and then I optimize an image, I must not see the quota updated in the admin bar. Then I click the refresh button, the quota must be updated.
- In the Imagify admin bar, there is a refresh icon. When I have a free plan and users/me response cached in transient, and then I update my plan on the Imagify website, I must not see the new plan in the Imagify admin bar.. Then I click the refresh button, the plan must be updated.

**Comment by remyperona** [comment]
The main issue here is the fact that the API call is done during the instantiation of the `User` class, in its constructor https://github.com/wp-media/imagify-plugin/blob/e1cd33b42852cd0850f5f8d1826ec1e03125d1df/classes/User/User.php#L127

A possible approach would be to move this and the properties setup into a setter method instead, so that the class can be used as a dependency and instantiated as needed, but the API call would happen just in time instead of on loading.

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
Going with what @remyperona has stated above, this is part of the optimization to be applied for this issue, ideally we should not be doing API calls in a constructor.

To add to that, we also need to make the calls on demand and the way I suggest is that we do a combination of hover + short caching so we don't hit the API on every hover event as in a case where hover is done in a short time where nothing significant is expected to change, maybe we can cache for 5-10 mins.

However if we need to implement @MathieuLamiot Idea of longer caching with a refresh button, we might need to align with @wp-media/product for UI changes for better UX when adding this said button.

I'm with both suggestions( hover & long caching ) bearing in mind that @remyperona suggestions is mandatory from my POV so which ever option we pick, we still need to make that change to the User class.

### Estimate the effort ✅
[S]

**Comment by MathieuLamiot** [comment]
Long caching seems quite disrupting for the UI and can lead to display wrong information for a long time. The hover + short caching (5min as of today) approach seems promising. Maybe we can try this, and see how it helps with traffic after the release?
I am pretty confident it would have a great impact already 🤞 
Thanks for the ideas 🙏

**Comment by remyperona** [comment]
I think that's the best approach for now

**Comment by Khadreal** [comment]
We currently have a cache for the `get_imagify_user` method https://github.com/wp-media/imagify-plugin/blob/e1cd33b42852cd0850f5f8d1826ec1e03125d1df/inc/functions/api.php#L42 though or should we increase the duration ?
@jeawhanlee , @MathieuLamiot

**Comment by MathieuLamiot** [comment]
@Khadreal See [the discussion above](https://github.com/wp-media/imagify-plugin/issues/923#issuecomment-2523069160):
- The current caching itself is not enough to reduce traffic, hence the need for the hover strategy.
- Combining call on hover + short caching should provide good results.

So I think we should keep the current cache, and this PR should focus on making the call only when needed (when hovering as recommended by @jeawhanlee)

**Comment by Mai-Saad** [comment]
> With Imagify activated, when I clear the transients and browse admin pages (excluding bulk, settings) and not hovering the Imagify admin bar, no requests to users/me are done.

@MathieuLamiot @remyperona @piotrbak Shall we add to exclusion too the plugins page as while starter license, we will have the upgrade link in plugins list?
i.e
0- starter acccount
1- delete `imagify_user_cache`
2- refresh plugins page =>> now on PR, we have API request to imagify (probably to add this upgrade link). what do you think? What if license was growth (same is happening now) or infinite?


![Image](https://github.com/user-attachments/assets/38035d77-4d03-4e98-b686-6cba0ebb4d66)

**Comment by MathieuLamiot** [comment]
Ok to add it to the exclusions on my end: if it is needed for this page, then it's OK.

**Comment by piotrbak** [comment]
@Mai-Saad Nice catch
