### ISSUE TITLE
Update plugin family package

### ISSUE THREAD

**Issue by jeawhanlee** [wp-media/imagify-plugin#932]
Update plugin family package to include translation fixes.

**Comment by MathieuLamiot** [comment]
@wp-media/qa-team @piotrbak Should this be added to 2.2.4? It is a small thing but seems ready for 3 weeks already

**Comment by piotrbak** [comment]
@MathieuLamiot Is it a very safe enhancement?

**Comment by MathieuLamiot** [comment]
You can check with @jeawhanlee. I think the same has been merged to WP Rocket already.

**Comment by piotrbak** [comment]
@jeawhanlee wdyt?

**Comment by jeawhanlee** [comment]
@piotrbak  it's a safe enhancement, we are basically just using imagfiy translation domain.

**Comment by Mai-Saad** [comment]
@MathieuLamiot @jeawhanlee let's merge it then and we will do a smoke test during the prerelease
