### ISSUE TITLE
Incorrect display of infinite spelling on plan modal

### ISSUE THREAD

**Issue by jeawhanlee** [wp-media/imagify-plugin#934]
**Before submitting an issue please check that you’ve completed the following steps:**
- Made sure you’re on the latest version
- Used the search feature to ensure that the bug hasn’t been reported before

**Describe the bug**
We have a regression on the plan modal where the infinite plan is displayed as inifinite_3

**To Reproduce**
1. On Imagify settings page
2. Click on the upgrade now button on the right
3. See the infinite displayed as infinite_3

**Expected behavior**
The infinite should be displayed correctly

**Screenshots**
![Image](https://github.com/user-attachments/assets/500011ba-a34d-4dda-8b06-d07637150f39)

**Additional context**

**Acceptance Criteria (for WP Media team use only)**
Clear instructions for developers, to be added before the grooming

**Comment by remyperona** [comment]
Shouldn't the label we receive from the API be correctly formatted from the start?

**Comment by jeawhanlee** [comment]
@remyperona https://wp-media.slack.com/archives/CU0F6EGQ1/p1733481533342149?thread_ts=1733481229.966199&cid=CU0F6EGQ1
