### ISSUE TITLE
Handle image stats through background processing

### ISSUE THREAD

**Issue by jeawhanlee** [wp-media/imagify-plugin#939]
**Is your feature request related to a problem? Please describe.**
Currently the stats processing logic has some complex queries which runs on the main thread and is render blocking.

**Describe the solution you'd like**
We need to port this logic from the main thread to run in the background instead. See details [here](https://github.com/wp-media/imagify-plugin/issues/632#issuecomment-2518158537) and in the following comments.

**Describe alternatives you've considered**

**Additional context**

**Comment by MathieuLamiot** [comment]
Discussio about flaws in the approach here: https://wp-media.slack.com/archives/CU0F6EGQ1/p1734535227194059
