### ISSUE TITLE
Hide the Imagify data in the Media Library filters

### ISSUE THREAD

**Issue by piotrbak** [wp-media/imagify-plugin#944]
**Context**
As a user, I don't want to see the number of optimized/unoptimized/error images in the filter dropdown in the Media Library context
![Image](https://github.com/user-attachments/assets/8e456e75-4cb3-4c1b-b83d-f3a6d334bf65)

**Acceptance Criteria**
1. We'll introduce a filter to hide the numbers in the `()` in the dropdown
2. The SQL query calculating those numbers shouldn't happen when the filter is active
3. When the filter is deactivated, we'll preserve the current behaviour
4. The filter will be activated by default

**Comment by Mai-Saad** [comment]
@wp-media/engineering-plugin-team Do we expect those slow queries not to exist anymore when accessing the media library? any other specific queries will be affected?
![Image](https://github.com/user-attachments/assets/b641ee98-9ef4-4ea2-ae61-e7a556386ae0)

**Comment by Mai-Saad** [comment]
related initial test plan https://wpmediaqa.testrail.io/index.php?/runs/view/943&group_by=cases:section_id&group_order=asc (may be updated as per code changes)

**Comment by jeawhanlee** [comment]
### Scope a solution ✅
In inc/admin/upload.php -> `_imagify_attachments_filter_dropdown`
- Add a new filter (imagify_display_library_stats) and set to false by default, when the filter is true, we call these functions to calculate the stats
https://github.com/wp-media/imagify-plugin/blob/4fd088118e756d9fb7b2f7eee556d223342e0a5f/inc/admin/upload.php#L54-L56 

### Estimate the effort ✅
[XS]

**Comment by Khadreal** [comment]
LGTM
